ECIF feature generation

In [1]:

import numpy as np
import pandas as pd
from os import listdir
from rdkit import Chem
from scipy.spatial.distance import cdist
from itertools import product
from rdkit.ML.Descriptors.MoleculeDescriptors import MolecularDescriptorCalculator

In [2]:

# Possible predefined protein atoms
ECIF_ProteinAtoms = ['C;4;1;3;0;0', 'C;4;2;1;1;1', 'C;4;2;2;0;0', 'C;4;2;2;0;1',
                     'C;4;3;0;0;0', 'C;4;3;0;1;1', 'C;4;3;1;0;0', 'C;4;3;1;0;1',
                     'C;5;3;0;0;0', 'C;6;3;0;0;0', 'N;3;1;2;0;0', 'N;3;2;0;1;1',
                     'N;3;2;1;0;0', 'N;3;2;1;1;1', 'N;3;3;0;0;1', 'N;4;1;2;0;0',
                     'N;4;1;3;0;0', 'N;4;2;1;0;0', 'O;2;1;0;0;0', 'O;2;1;1;0;0',
                     'S;2;1;1;0;0', 'S;2;2;0;0;0']

# Possible ligand atoms according to the PDBbind 2016 "refined set"
ECIF_LigandAtoms = ['Br;1;1;0;0;0', 'C;3;3;0;1;1', 'C;4;1;1;0;0', 'C;4;1;2;0;0',
                     'C;4;1;3;0;0', 'C;4;2;0;0;0', 'C;4;2;1;0;0', 'C;4;2;1;0;1',
                     'C;4;2;1;1;1', 'C;4;2;2;0;0', 'C;4;2;2;0;1', 'C;4;3;0;0;0',
                     'C;4;3;0;0;1', 'C;4;3;0;1;1', 'C;4;3;1;0;0', 'C;4;3;1;0;1',
                     'C;4;4;0;0;0', 'C;4;4;0;0;1', 'C;5;3;0;0;0', 'C;5;3;0;1;1',
                     'C;6;3;0;0;0', 'Cl;1;1;0;0;0', 'F;1;1;0;0;0', 'I;1;1;0;0;0',
                     'N;3;1;0;0;0', 'N;3;1;1;0;0', 'N;3;1;2;0;0', 'N;3;2;0;0;0',
                     'N;3;2;0;0;1', 'N;3;2;0;1;1', 'N;3;2;1;0;0', 'N;3;2;1;0;1',
                     'N;3;2;1;1;1', 'N;3;3;0;0;0', 'N;3;3;0;0;1', 'N;3;3;0;1;1',
                     'N;4;1;2;0;0', 'N;4;1;3;0;0', 'N;4;2;1;0;0', 'N;4;2;2;0;0',
                     'N;4;2;2;0;1', 'N;4;3;0;0;0', 'N;4;3;0;0;1', 'N;4;3;1;0;0',
                     'N;4;3;1;0;1', 'N;4;4;0;0;0', 'N;4;4;0;0;1', 'N;5;2;0;0;0',
                     'N;5;3;0;0;0', 'N;5;3;0;1;1', 'O;2;1;0;0;0', 'O;2;1;1;0;0',
                     'O;2;2;0;0;0', 'O;2;2;0;0;1', 'O;2;2;0;1;1', 'P;5;4;0;0;0',
                     'P;6;4;0;0;0', 'P;6;4;0;0;1', 'P;7;4;0;0;0', 'S;2;1;0;0;0',
                     'S;2;1;1;0;0', 'S;2;2;0;0;0', 'S;2;2;0;0;1', 'S;2;2;0;1;1',
                     'S;3;3;0;0;0', 'S;3;3;0;0;1', 'S;4;3;0;0;0', 'S;6;4;0;0;0',
                     'S;6;4;0;0;1', 'S;7;4;0;0;0']

PossibleECIF = [i[0]+"-"+i[1] for i in product(ECIF_ProteinAtoms, ECIF_LigandAtoms)]

In [3]:
ELEMENTS_ProteinAtoms = ["C","N","O", "S"]
ELEMENTS_LigandAtoms = ["Br", "C", "Cl", "F", "I", "N", "O", "P", "S"]
PossibleELEMENTS = [i[0]+"-"+i[1] for i in product(ELEMENTS_ProteinAtoms, ELEMENTS_LigandAtoms)]

In [4]:
LigandDescriptors = ['MaxEStateIndex', 'MinEStateIndex', 'MaxAbsEStateIndex', 'MinAbsEStateIndex',
                      'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons',
                      'FpDensityMorgan1', 'FpDensityMorgan2', 'FpDensityMorgan3', 'BalabanJ',
                      'BertzCT', 'Chi0', 'Chi0n', 'Chi0v', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n',
                      'Chi2v', 'Chi3n', 'Chi3v', 'Chi4n', 'Chi4v', 'HallKierAlpha', 'Kappa1',
                      'Kappa2', 'Kappa3', 'LabuteASA', 'PEOE_VSA14', 'SMR_VSA1', 'SMR_VSA10',
                      'SMR_VSA2', 'SMR_VSA3', 'SMR_VSA4', 'SMR_VSA5', 'SMR_VSA6', 'SMR_VSA7',
                      'SMR_VSA9', 'SlogP_VSA1', 'SlogP_VSA10', 'SlogP_VSA11', 'SlogP_VSA12',
                      'SlogP_VSA2', 'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA5', 'SlogP_VSA6',
                      'SlogP_VSA7', 'SlogP_VSA8', 'TPSA', 'EState_VSA1', 'EState_VSA10',
                      'EState_VSA11', 'EState_VSA2', 'EState_VSA3', 'EState_VSA4', 'EState_VSA5',
                      'EState_VSA6', 'EState_VSA7', 'EState_VSA8', 'EState_VSA9', 'VSA_EState1',
                      'VSA_EState10', 'VSA_EState2', 'VSA_EState3', 'VSA_EState4', 'VSA_EState5',
                      'VSA_EState6', 'VSA_EState7', 'VSA_EState8', 'VSA_EState9', 'FractionCSP3',
                      'HeavyAtomCount', 'NHOHCount', 'NOCount', 'NumAliphaticCarbocycles',
                      'NumAliphaticHeterocycles', 'NumAliphaticRings', 'NumAromaticCarbocycles',
                      'NumAromaticHeterocycles', 'NumAromaticRings', 'NumHAcceptors', 'NumHDonors',
                      'NumHeteroatoms', 'NumRotatableBonds', 'NumSaturatedCarbocycles',
                      'NumSaturatedHeterocycles', 'NumSaturatedRings', 'RingCount', 'MolLogP',
                      'MolMR', 'fr_Al_COO', 'fr_Al_OH', 'fr_Al_OH_noTert', 'fr_ArN', 'fr_Ar_N',
                      'fr_Ar_NH', 'fr_Ar_OH', 'fr_COO', 'fr_COO2', 'fr_C_O', 'fr_C_O_noCOO',
                      'fr_C_S', 'fr_HOCCN', 'fr_Imine', 'fr_NH0', 'fr_NH1', 'fr_NH2', 'fr_N_O',
                      'fr_Ndealkylation1', 'fr_Ndealkylation2', 'fr_Nhpyrrole', 'fr_SH', 'fr_aldehyde',
                      'fr_alkyl_carbamate', 'fr_alkyl_halide', 'fr_allylic_oxid', 'fr_amide',
                      'fr_amidine', 'fr_aniline', 'fr_aryl_methyl', 'fr_azo', 'fr_barbitur',
                      'fr_benzene', 'fr_bicyclic', 'fr_dihydropyridine', 'fr_epoxide', 'fr_ester',
                      'fr_ether', 'fr_furan', 'fr_guanido', 'fr_halogen', 'fr_hdrzine', 'fr_hdrzone',
                      'fr_imidazole', 'fr_imide', 'fr_isocyan', 'fr_isothiocyan', 'fr_ketone',
                      'fr_ketone_Topliss', 'fr_lactam', 'fr_lactone', 'fr_methoxy', 'fr_morpholine',
                      'fr_nitrile', 'fr_nitro', 'fr_nitro_arom', 'fr_nitroso', 'fr_oxazole',
                      'fr_oxime', 'fr_para_hydroxylation', 'fr_phenol', 'fr_phenol_noOrthoHbond',
                      'fr_piperdine', 'fr_piperzine', 'fr_priamide', 'fr_pyridine', 'fr_quatN',
                      'fr_sulfide', 'fr_sulfonamd', 'fr_sulfone', 'fr_term_acetylene', 'fr_tetrazole',
                      'fr_thiazole', 'fr_thiocyan', 'fr_thiophene', 'fr_urea']

DescCalc = MolecularDescriptorCalculator(LigandDescriptors)

In [5]:
def GetAtomType(atom):
# This function takes an atom in a molecule and returns its type as defined for ECIF
    
    AtomType = [atom.GetSymbol(),
                str(atom.GetExplicitValence()),
                str(len([x.GetSymbol() for x in atom.GetNeighbors() if x.GetSymbol() != "H"])),
                str(len([x.GetSymbol() for x in atom.GetNeighbors() if x.GetSymbol() == "H"])),
                str(int(atom.GetIsAromatic())),
                str(int(atom.IsInRing())), 
               ]

    return(";".join(AtomType))

In [6]:
def LoadSDFasDF(SDF):
# This function takes an SDF for a ligand as input and returns it as a pandas DataFrame with its atom types labeled according to ECIF
    
    m = Chem.MolFromMolFile(SDF, sanitize=False)
    m.UpdatePropertyCache(strict=False)
    
    ECIF_atoms = []

    for atom in m.GetAtoms():
        if atom.GetSymbol() != "H": # Include only non-hydrogen atoms
            entry = [int(atom.GetIdx())]
            entry.append(GetAtomType(atom))
            pos = m.GetConformer().GetAtomPosition(atom.GetIdx())
            entry.append(float("{0:.4f}".format(pos.x)))
            entry.append(float("{0:.4f}".format(pos.y)))
            entry.append(float("{0:.4f}".format(pos.z)))
            ECIF_atoms.append(entry)

    df = pd.DataFrame(ECIF_atoms)
    df.columns = ["ATOM_INDEX", "ECIF_ATOM_TYPE","X","Y","Z"]
    if len(set(df["ECIF_ATOM_TYPE"]) - set(ECIF_LigandAtoms)) > 0:
        print("WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.")
    return(df)

In [7]:
Atom_Keys=pd.read_csv("/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/PDB_Atom_Keys.csv", sep=",")
def LoadPDBasDF(PDB):
# This function takes a PDB for a protein as input and returns it as a pandas DataFrame with its atom types labeled according to ECIF

    ECIF_atoms = []
    
    f = open(PDB)
    for i in f:
        if i[:4] == "ATOM":
            # Include only non-hydrogen atoms
            if (len(i[12:16].replace(" ","")) < 4 and i[12:16].replace(" ","")[0] != "H") or (len(i[12:16].replace(" ","")) == 4 and i[12:16].replace(" ","")[1] != "H" and i[12:16].replace(" ","")[0] != "H"):
                ECIF_atoms.append([int(i[6:11]),
                         i[17:20]+"-"+i[12:16].replace(" ",""),
                         float(i[30:38]),
                         float(i[38:46]),
                         float(i[46:54])
                        ])
                
    f.close()
    
    df = pd.DataFrame(ECIF_atoms, columns=["ATOM_INDEX","PDB_ATOM","X","Y","Z"])
    df = df.merge(Atom_Keys, left_on='PDB_ATOM', right_on='PDB_ATOM')[["ATOM_INDEX", "ECIF_ATOM_TYPE", "X", "Y", "Z"]].sort_values(by="ATOM_INDEX").reset_index(drop=True)
    if list(df["ECIF_ATOM_TYPE"].isna()).count(True) > 0:
        print("WARNING: Protein contains unsupported atom types. Only supported atom-type pairs are counted.")
    return(df)

In [8]:
def GetPLPairs(PDB_protein, SDF_ligand, distance_cutoff=6.0):
# This function returns the protein-ligand atom-type pairs for a given distance cutoff
    
    # Load both structures as pandas DataFrames
    Target = LoadPDBasDF(PDB_protein)
    Ligand = LoadSDFasDF(SDF_ligand)
    
    # Take all atoms from the target within a cubic box around the ligand considering the "distance_cutoff criterion"
    for i in ["X","Y","Z"]:
        Target = Target[Target[i] < float(Ligand[i].max())+distance_cutoff]
        Target = Target[Target[i] > float(Ligand[i].min())-distance_cutoff]
    
    # Get all possible pairs
    Pairs = list(product(Target["ECIF_ATOM_TYPE"], Ligand["ECIF_ATOM_TYPE"]))
    Pairs = [x[0]+"-"+x[1] for x in Pairs]
    Pairs = pd.DataFrame(Pairs, columns=["ECIF_PAIR"])
    Distances = cdist(Target[["X","Y","Z"]], Ligand[["X","Y","Z"]], metric="euclidean")
    Distances = Distances.reshape(Distances.shape[0]*Distances.shape[1],1)
    Distances = pd.DataFrame(Distances, columns=["DISTANCE"])

    Pairs = pd.concat([Pairs,Distances], axis=1)
    Pairs = Pairs[Pairs["DISTANCE"] <= distance_cutoff].reset_index(drop=True)
    # Pairs from ELEMENTS could be easily obtained froms pairs from ECIF
    Pairs["ELEMENTS_PAIR"] = [x.split("-")[0].split(";")[0]+"-"+x.split("-")[1].split(";")[0] for x in Pairs["ECIF_PAIR"]]
    return Pairs

In [9]:
def GetECIF(PDB_protein, SDF_ligand, distance_cutoff=6.0):
    # Main function for the calculation of ECIF
    Pairs = GetPLPairs(PDB_protein, SDF_ligand, distance_cutoff=distance_cutoff)
    print(f"{prefix}: {len(Pairs)} pairs found")
    # Check if Pairs is empty
    if Pairs.empty:
        return None  # Nothing to calculate
    
    ECIF = [list(Pairs["ECIF_PAIR"]).count(x) for x in PossibleECIF]
    return ECIF

In [10]:
def GetELEMENTS(PDB_protein, SDF_ligand, distance_cutoff=6.0):
# Function for the calculation of ELEMENTS
    Pairs = GetPLPairs(PDB_protein, SDF_ligand, distance_cutoff=distance_cutoff)
    ELEMENTS = [list(Pairs["ELEMENTS_PAIR"]).count(x) for x in PossibleELEMENTS]
    return ELEMENTS

In [11]:
def GetRDKitDescriptors(SDF):
# Function for the calculation of ligand descriptors
    mol = Chem.MolFromMolFile(SDF, sanitize=False)
    mol.UpdatePropertyCache(strict=False)
    Chem.GetSymmSSSR(mol)
    return DescCalc.CalcDescriptors(mol)

Generation ECIF descriptors for training data

In [79]:
import os
import pandas as pd

protein_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/proteins_pdb_train"
ligand_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/ligand_train_rdkit"

ligand_files = [f for f in os.listdir(ligand_dir) if f.endswith(".sdf")]
results = []

for ligand_file in ligand_files:
    prefix = ligand_file.split("_")[0]  # e.g., "1a1b"
    protein_file = os.path.join(protein_dir, f"{prefix}_receptor.pdb")
    ligand_path = os.path.join(ligand_dir, ligand_file)

    if not os.path.exists(protein_file):
        print(f"⚠️ Protein file not found for {prefix}, skipping...")
        continue

    print(f"✅ Processing {prefix} ...")

    # === TRY-EXCEPT to skip any problematic complex ===
    try:
        ecif_vector = GetECIF(protein_file, ligand_path)
        if ecif_vector is None or len(ecif_vector) == 0:
            print(f"⚠️ Skipping {prefix} — no ECIF features generated.")
            continue
        # Add Complex ID as first column
        ecif_vector = [prefix] + ecif_vector
        results.append(ecif_vector)

    except Exception as e:
        print(f"❌ Skipping {prefix} due to error: {e}")
        continue

# Convert to DataFrame
if results:
    # First column = Complex_ID, rest = ECIF headers
    headers = ["Complex_ID"] + PossibleECIF
    df_ecif = pd.DataFrame(results, columns=headers)
    df_ecif.to_csv("ECIF_descriptors_train.csv", index=False)
    print(f"\n✅ ECIF descriptors saved to: ECIF_descriptors_train.csv")
else:
    print("❌ No ECIF features generated. Check your input files.")

✅ Processing 3r02 ...
3r02: 488 pairs found
✅ Processing 6c2t ...
6c2t: 674 pairs found
✅ Processing 5t31 ...
5t31: 442 pairs found
✅ Processing 4eop ...
4eop: 693 pairs found
✅ Processing 2ghg ...
2ghg: 735 pairs found
✅ Processing 4njd ...
4njd: 610 pairs found
✅ Processing 4acm ...
4acm: 819 pairs found
✅ Processing 1svh ...
1svh: 989 pairs found
✅ Processing 5l2t ...
5l2t: 715 pairs found
✅ Processing 4tv3 ...
4tv3: 609 pairs found
✅ Processing 5m55 ...
5m55: 493 pairs found
✅ Processing 4rx7 ...
4rx7: 684 pairs found
✅ Processing 4qms ...
4qms: 680 pairs found
✅ Processing 2wxl ...
2wxl: 699 pairs found
✅ Processing 3uyt ...
3uyt: 634 pairs found
✅ Processing 4jbo ...
4jbo: 998 pairs found
✅ Processing 4qp7 ...
4qp7: 368 pairs found
✅ Processing 3el7 ...
3el7: 927 pairs found
✅ Processing 5kkr ...
5kkr: 717 pairs found
✅ Processing 1unl ...
1unl: 610 pairs found
✅ Processing 2brg ...
2brg: 572 pairs found
✅ Processing 4jaj ...
4jaj: 379 pairs found
✅ Processing 4xg3 ...
4xg3: 678 pairs found
✅ Processing 3qd0 ...
3qd0: 704 pairs found
✅ Processing 4pte ...
4pte: 537 pairs found
✅ Processing 2xrw ...
2xrw: 660 pairs found
✅ Processing 6dud ...
6dud: 526 pairs found
✅ Processing 4ckr ...
4ckr: 1026 pairs found
✅ Processing 3s2p ...
3s2p: 534 pairs found
✅ Processing 1e9h ...
1e9h: 645 pairs found
✅ Processing 4l52 ...
4l52: 708 pairs found
✅ Processing 4waf ...
4waf: 644 pairs found
✅ Processing 4o0v ...
4o0v: 711 pairs found
✅ Processing 3r7q ...
3r7q: 523 pairs found
✅ Processing 1owi ...
1owi: 628 pairs found
✅ Processing 1o4j ...
1o4j: 260 pairs found
✅ Processing 4ehe ...
4ehe: 717 pairs found
✅ Processing 4hcu ...
4hcu: 792 pairs found
✅ Processing 3vnt ...
3vnt: 1024 pairs found
✅ Processing 4rcg ...
4rcg: 680 pairs found
✅ Processing 4v04 ...
4v04: 1469 pairs found
✅ Processing 2jdt ...
2jdt: 702 pairs found
✅ Processing 4x21 ...
4x21: 592 pairs found
✅ Processing 6fex ...
6fex: 919 pairs found
✅ Processing 4m7x ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4m7x: 830 pairs found
✅ Processing 3wzu ...
3wzu: 530 pairs found
✅ Processing 2wu7 ...
2wu7: 533 pairs found
✅ Processing 3nga ...
3nga: 618 pairs found
✅ Processing 2z60 ...
2z60: 726 pairs found
✅ Processing 4nw5 ...
4nw5: 708 pairs found
✅ Processing 6fyv ...
6fyv: 567 pairs found
✅ Processing 3n51 ...
3n51: 710 pairs found
✅ Processing 3f3t ...
3f3t: 729 pairs found
✅ Processing 1hiy ...
1hiy: 451 pairs found
✅ Processing 2wd1 ...
❌ Skipping 2wd1 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5d11 ...
5d11: 595 pairs found
✅ Processing 5z1c ...
5z1c: 318 pairs found
✅ Processing 1ung ...
1ung: 465 pairs found
✅ Processing 6rln ...
6rln: 887 pairs found
✅ Processing 2ycs ...
2ycs: 607 pairs found
✅ Processing 4g9c ...
4g9c: 1044 pairs found
✅ Processing 6b3e ...
6b3e: 724 pairs found
✅ Processing 5xv7 ...
5xv7: 725 pairs found
✅ Processing 4m7y ...
4m7y: 696 pairs found
✅ Processing 5wbp ...
5wbp: 384 pairs found
✅ Processing 4fz6 ...
4fz6: 539 pairs found
✅ Processing 3fzr ...
3fzr: 703 pairs found
✅ Processing 5ar8 ...
5ar8: 1066 pairs found
✅ Processing 3qcq ...
3qcq: 509 pairs found
✅ Processing 4lgh ...
4lgh: 569 pairs found
✅ Processing 5mxx ...
5mxx: 621 pairs found
✅ Processing 1o47 ...
1o47: 691 pairs found
✅ Processing 1zrz ...
1zrz: 614 pairs found
✅ Processing 3qri ...
3qri: 1091 pairs found
✅ Processing 1fvv ...
1fvv: 742 pairs found
✅ Processing 4hvh ...
4hvh: 487 pairs found
✅ Processing 3a4p ...
3a4p: 674 pairs found
✅ Processing 5ort ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5ort: 575 pairs found
✅ Processing 4l8m ...
4l8m: 1105 pairs found
✅ Processing 3s3i ...
3s3i: 630 pairs found
✅ Processing 5orx ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5orx: 573 pairs found
✅ Processing 1uvr ...
1uvr: 621 pairs found
✅ Processing 3uib ...
3uib: 556 pairs found
✅ Processing 2c69 ...
❌ Skipping 2c69 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5tq7 ...
5tq7: 759 pairs found
✅ Processing 3f69 ...
3f69: 764 pairs found
✅ Processing 2w1e ...
❌ Skipping 2w1e due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4z9l ...
4z9l: 375 pairs found
✅ Processing 4bdf ...
4bdf: 332 pairs found
✅ Processing 5nhh ...
5nhh: 670 pairs found
✅ Processing 1zzl ...
1zzl: 659 pairs found
✅ Processing 5hvy ...
5hvy: 866 pairs found
✅ Processing 3lpb ...
3lpb: 765 pairs found
✅ Processing 5auu ...
5auu: 608 pairs found
✅ Processing 4idt ...
4idt: 532 pairs found
✅ Processing 6edl ...
6edl: 592 pairs found
✅ Processing 3wf6 ...
3wf6: 590 pairs found
✅ Processing 5j7s ...
5j7s: 600 pairs found
✅ Processing 4op1 ...
4op1: 802 pairs found
✅ Processing 3thb ...
3thb: 755 pairs found
✅ Processing 1wbo ...
1wbo: 230 pairs found
✅ Processing 2c6l ...
2c6l: 686 pairs found
✅ Processing 3byu ...
3byu: 1096 pairs found
✅ Processing 2ok1 ...
2ok1: 633 pairs found
✅ Processing 4h1j ...
4h1j: 887 pairs found
✅ Processing 4o0t ...
4o0t: 724 pairs found
✅ Processing 4ptg ...
4ptg: 558 pairs found
✅ Processing 6dkb ...
6dkb: 898 pairs found
✅ Processing 3pxz ...
3pxz: 288 pairs found
✅ Processing 3rtp ...
3rtp: 578 pairs found
✅ Processing 3kvx ...
3kvx: 854 pairs found
✅ Processing 2y9q ...
2y9q: 764 pairs found
✅ Processing 4enx ...
❌ Skipping 4enx due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 2yoh ...
❌ Skipping 2yoh due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4unr ...
4unr: 850 pairs found
✅ Processing 2x8i ...
2x8i: 525 pairs found
✅ Processing 3qu0 ...
3qu0: 670 pairs found
✅ Processing 4qtd ...
4qtd: 888 pairs found
✅ Processing 6m8d ...
6m8d: 457 pairs found
✅ Processing 3wf8 ...
3wf8: 782 pairs found
✅ Processing 4qmw ...
4qmw: 536 pairs found
✅ Processing 1o4n ...
1o4n: 201 pairs found
✅ Processing 6ge0 ...
6ge0: 947 pairs found
✅ Processing 2uzv ...
2uzv: 803 pairs found
✅ Processing 4eym ...
4eym: 767 pairs found
✅ Processing 4d1s ...
4d1s: 723 pairs found
✅ Processing 3uxm ...
3uxm: 566 pairs found
✅ Processing 4hct ...
4hct: 853 pairs found
✅ Processing 4fc0 ...
4fc0: 1049 pairs found
✅ Processing 4pvv ...
4pvv: 578 pairs found
✅ Processing 6h0u ...
6h0u: 581 pairs found
✅ Processing 5aep ...
5aep: 606 pairs found
✅ Processing 1ykr ...
1ykr: 747 pairs found
✅ Processing 4lmu ...
4lmu: 538 pairs found
✅ Processing 5o0j ...
5o0j: 608 pairs found
✅ Processing 5t2d ...
5t2d: 695 pairs found
✅ Processing 5ory ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5ory: 580 pairs found
✅ Processing 2hz0 ...
2hz0: 966 pairs found
✅ Processing 1pmn ...
1pmn: 690 pairs found
✅ Processing 4r3c ...
4r3c: 563 pairs found
✅ Processing 4i5p ...
4i5p: 538 pairs found
✅ Processing 6dkg ...
6dkg: 271 pairs found
✅ Processing 2btr ...
2btr: 477 pairs found
✅ Processing 3vf9 ...
3vf9: 480 pairs found
✅ Processing 4erw ...
4erw: 778 pairs found
✅ Processing 2pzi ...
2pzi: 472 pairs found
✅ Processing 1xh7 ...
1xh7: 1132 pairs found
✅ Processing 3psb ...
3psb: 627 pairs found
✅ Processing 6e2o ...
6e2o: 781 pairs found
✅ Processing 3umw ...
3umw: 607 pairs found
✅ Processing 4nus ...
4nus: 564 pairs found
✅ Processing 4px6 ...
4px6: 699 pairs found
✅ Processing 5gjd ...
5gjd: 977 pairs found
✅ Processing 2c1a ...
2c1a: 704 pairs found
✅ Processing 3zm4 ...
3zm4: 469 pairs found
✅ Processing 2yir ...
❌ Skipping 2yir due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4bid ...
4bid: 773 pairs found
✅ Processing 4pp9 ...
4pp9: 606 pairs found
✅ Processing 1vj9 ...
1vj9: 893 pairs found
✅ Processing 4qmx ...
4qmx: 680 pairs found
✅ Processing 1oi9 ...
1oi9: 625 pairs found
✅ Processing 4an2 ...
4an2: 805 pairs found
✅ Processing 3zbf ...
3zbf: 545 pairs found
✅ Processing 3nzu ...
3nzu: 585 pairs found
✅ Processing 4ebv ...
4ebv: 664 pairs found
✅ Processing 4jbp ...
4jbp: 1019 pairs found
✅ Processing 3uix ...
3uix: 522 pairs found
✅ Processing 2c68 ...
2c68: 643 pairs found
✅ Processing 3el8 ...
3el8: 827 pairs found
✅ Processing 2w1h ...
2w1h: 639 pairs found
✅ Processing 1gjd ...
1gjd: 638 pairs found
✅ Processing 4qfs ...
4qfs: 807 pairs found
✅ Processing 6m8a ...
6m8a: 434 pairs found
✅ Processing 3l9n ...
3l9n: 644 pairs found
✅ Processing 4eh8 ...
4eh8: 641 pairs found
✅ Processing 3mj1 ...
3mj1: 646 pairs found
✅ Processing 4m3q ...
4m3q: 544 pairs found
✅ Processing 6nzp ...
6nzp: 829 pairs found
✅ Processing 4fod ...
4fod: 845 pairs found
✅ Processing 4lkm ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4lkm: 982 pairs found
✅ Processing 5bvd ...
5bvd: 847 pairs found
✅ Processing 2hzi ...
2hzi: 802 pairs found
✅ Processing 4ykn ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4ykn: 667 pairs found
✅ Processing 4hys ...
4hys: 443 pairs found
✅ Processing 2o5k ...
2o5k: 681 pairs found
✅ Processing 2vwv ...
2vwv: 550 pairs found
✅ Processing 4obq ...
4obq: 632 pairs found
✅ Processing 2yak ...
2yak: 127 pairs found
✅ Processing 5jgb ...
5jgb: 554 pairs found
✅ Processing 6bkh ...
6bkh: 832 pairs found
✅ Processing 6aud ...
6aud: 672 pairs found
✅ Processing 2q8g ...
2q8g: 668 pairs found
✅ Processing 5ghv ...
❌ Skipping 5ghv due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5ax9 ...
5ax9: 684 pairs found
✅ Processing 5t27 ...
5t27: 605 pairs found
✅ Processing 4yur ...
❌ Skipping 4yur due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4rvk ...
4rvk: 635 pairs found
✅ Processing 4u79 ...
4u79: 886 pairs found
✅ Processing 3mvl ...
3mvl: 795 pairs found
✅ Processing 3ot3 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
3ot3: 1175 pairs found
✅ Processing 4ckj ...
4ckj: 460 pairs found
✅ Processing 3t9t ...
3t9t: 689 pairs found
✅ Processing 3u4u ...
3u4u: 671 pairs found
✅ Processing 4x7h ...
4x7h: 1197 pairs found
✅ Processing 3piz ...
3piz: 592 pairs found
✅ Processing 4dtk ...
4dtk: 554 pairs found
✅ Processing 4nw6 ...
4nw6: 731 pairs found
✅ Processing 2og8 ...
2og8: 1036 pairs found
✅ Processing 3gpe ...
3gpe: 245 pairs found
✅ Processing 4g11 ...
4g11: 565 pairs found
✅ Processing 3nuu ...
3nuu: 267 pairs found
✅ Processing 5etm ...
5etm: 598 pairs found
✅ Processing 5g2n ...
5g2n: 760 pairs found
✅ Processing 4w4w ...
4w4w: 731 pairs found
✅ Processing 4q1b ...
4q1b: 721 pairs found
✅ Processing 6op9 ...
6op9: 682 pairs found
✅ Processing 2gnh ...
2gnh: 487 pairs found
✅ Processing 3fxz ...
3fxz: 427 pairs found
✅ Processing 2b7a ...
2b7a: 585 pairs found
✅ Processing 4afe ...
4afe: 775 pairs found
✅ Processing 4n70 ...
4n70: 713 pairs found
✅ Processing 6pdj ...
6pdj: 887 pairs found
✅ Processing 1w1g ...
1w1g: 353 pairs found
✅ Processing 5i0b ...
5i0b: 417 pairs found
✅ Processing 4i6f ...
4i6f: 695 pairs found
✅ Processing 2wxg ...
2wxg: 887 pairs found
✅ Processing 3dbd ...
3dbd: 666 pairs found
✅ Processing 4ark ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4ark: 616 pairs found
✅ Processing 2ofv ...
2ofv: 937 pairs found
✅ Processing 5nhl ...
5nhl: 638 pairs found
✅ Processing 2yit ...
2yit: 681 pairs found
✅ Processing 4i6q ...
4i6q: 334 pairs found
✅ Processing 5nhv ...
5nhv: 566 pairs found
✅ Processing 5h8b ...
5h8b: 647 pairs found
✅ Processing 4o6e ...
4o6e: 671 pairs found
✅ Processing 4ztn ...
4ztn: 736 pairs found
✅ Processing 4ph4 ...
4ph4: 593 pairs found
✅ Processing 4rvt ...
4rvt: 579 pairs found
✅ Processing 1nlp ...
1nlp: 691 pairs found
✅ Processing 1h07 ...
1h07: 773 pairs found
✅ Processing 6b2p ...
6b2p: 555 pairs found
✅ Processing 2r9s ...
2r9s: 654 pairs found
✅ Processing 1o3p ...
1o3p: 664 pairs found
✅ Processing 4mxc ...
4mxc: 1188 pairs found
✅ Processing 4cnh ...
4cnh: 491 pairs found
✅ Processing 5f20 ...
5f20: 627 pairs found
✅ Processing 1w1d ...
1w1d: 353 pairs found
✅ Processing 4a4o ...
4a4o: 903 pairs found
✅ Processing 5jic ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5jic: 841 pairs found
✅ Processing 4c36 ...
4c36: 611 pairs found
✅ Processing 5khx ...
5khx: 546 pairs found
✅ Processing 4ehv ...
4ehv: 544 pairs found
✅ Processing 5m4k ...
5m4k: 513 pairs found
✅ Processing 2zdx ...
2zdx: 452 pairs found
✅ Processing 4hni ...
4hni: 583 pairs found
✅ Processing 1bl6 ...
1bl6: 432 pairs found
✅ Processing 4zim ...
4zim: 638 pairs found
✅ Processing 2c5n ...
2c5n: 586 pairs found
✅ Processing 5vil ...
5vil: 747 pairs found
✅ Processing 5wbq ...
5wbq: 501 pairs found
✅ Processing 6sfj ...
6sfj: 990 pairs found
✅ Processing 5tq6 ...
5tq6: 657 pairs found
✅ Processing 5d10 ...
5d10: 519 pairs found
✅ Processing 3r9h ...
3r9h: 744 pairs found
✅ Processing 6rfj ...
6rfj: 791 pairs found
✅ Processing 5vc5 ...
5vc5: 793 pairs found
✅ Processing 4acg ...
4acg: 778 pairs found
✅ Processing 4eos ...
4eos: 662 pairs found
✅ Processing 1q3w ...
❌ Skipping 1q3w due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3wi6 ...
3wi6: 439 pairs found
✅ Processing 2f4j ...
2f4j: 748 pairs found
✅ Processing 5dhq ...
5dhq: 764 pairs found
✅ Processing 5da3 ...
5da3: 653 pairs found
✅ Processing 6sze ...
6sze: 396 pairs found
✅ Processing 2cn8 ...
2cn8: 478 pairs found
✅ Processing 3zos ...
3zos: 1087 pairs found
✅ Processing 2fum ...
2fum: 666 pairs found
✅ Processing 5m44 ...
5m44: 472 pairs found
✅ Processing 5one ...
5one: 706 pairs found
✅ Processing 1gja ...
1gja: 573 pairs found
✅ Processing 1o5b ...
1o5b: 460 pairs found
✅ Processing 2xne ...
2xne: 566 pairs found
✅ Processing 3vry ...
3vry: 723 pairs found
✅ Processing 5j5x ...
❌ Skipping 5j5x due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5j1w ...
5j1w: 404 pairs found
✅ Processing 5jzn ...
5jzn: 703 pairs found
✅ Processing 4hyi ...
4hyi: 713 pairs found
✅ Processing 3uol ...
3uol: 614 pairs found
✅ Processing 3gen ...
3gen: 734 pairs found
✅ Processing 6eip ...
6eip: 650 pairs found
✅ Processing 4bi0 ...
4bi0: 307 pairs found
✅ Processing 2vww ...
2vww: 700 pairs found
✅ Processing 2zv9 ...
2zv9: 474 pairs found
✅ Processing 3kf4 ...
3kf4: 801 pairs found
✅ Processing 3os3 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
3os3: 719 pairs found
✅ Processing 2iw8 ...
2iw8: 690 pairs found
✅ Processing 5xyx ...
5xyx: 483 pairs found
✅ Processing 4j53 ...
4j53: 757 pairs found
✅ Processing 2izx ...
2izx: 185 pairs found
✅ Processing 2xk8 ...
2xk8: 735 pairs found
✅ Processing 3upz ...
3upz: 379 pairs found
✅ Processing 3s4q ...
3s4q: 831 pairs found
✅ Processing 4wt6 ...
4wt6: 606 pairs found
✅ Processing 4qyg ...
4qyg: 606 pairs found
✅ Processing 1w2g ...
1w2g: 535 pairs found
✅ Processing 1oit ...
1oit: 642 pairs found
✅ Processing 2hxq ...
2hxq: 549 pairs found
✅ Processing 1x8b ...
1x8b: 636 pairs found
✅ Processing 3zrl ...
3zrl: 358 pairs found
✅ Processing 5ei8 ...
5ei8: 716 pairs found
✅ Processing 5d12 ...
5d12: 508 pairs found
✅ Processing 3ow3 ...
3ow3: 764 pairs found
✅ Processing 1jvp ...
1jvp: 775 pairs found
✅ Processing 4kp4 ...
4kp4: 949 pairs found
✅ Processing 6bod ...
6bod: 444 pairs found
✅ Processing 4qyh ...
4qyh: 586 pairs found
✅ Processing 5e7r ...
5e7r: 663 pairs found
✅ Processing 4m5l ...
4m5l: 554 pairs found
✅ Processing 3r21 ...
3r21: 611 pairs found
✅ Processing 2x8e ...
2x8e: 493 pairs found
✅ Processing 3s1h ...
3s1h: 698 pairs found
✅ Processing 5htb ...
5htb: 1422 pairs found
✅ Processing 2dq7 ...
2dq7: 714 pairs found
✅ Processing 4qp6 ...
4qp6: 228 pairs found
✅ Processing 4o91 ...
4o91: 978 pairs found
✅ Processing 3uoh ...
3uoh: 645 pairs found
✅ Processing 2x8d ...
2x8d: 380 pairs found
✅ Processing 3v8t ...
3v8t: 618 pairs found
✅ Processing 6b2q ...
6b2q: 601 pairs found
✅ Processing 3f9n ...
3f9n: 541 pairs found
✅ Processing 2bdj ...
2bdj: 789 pairs found
✅ Processing 5ih8 ...
5ih8: 535 pairs found
✅ Processing 4c37 ...
4c37: 603 pairs found
✅ Processing 2w1c ...
❌ Skipping 2w1c due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3wf9 ...
3wf9: 790 pairs found
✅ Processing 4gmy ...
4gmy: 485 pairs found
✅ Processing 5ttv ...
5ttv: 476 pairs found
✅ Processing 3fy0 ...
3fy0: 10 pairs found
✅ Processing 6ul8 ...
6ul8: 569 pairs found
✅ Processing 3piy ...
3piy: 745 pairs found
✅ Processing 4mq1 ...
4mq1: 824 pairs found
✅ Processing 3kga ...
3kga: 801 pairs found
✅ Processing 4flh ...
4flh: 704 pairs found
✅ Processing 2vu3 ...
2vu3: 622 pairs found
✅ Processing 4rx8 ...
4rx8: 703 pairs found
✅ Processing 5xgh ...
5xgh: 612 pairs found
✅ Processing 2duv ...
2duv: 658 pairs found
✅ Processing 4eh7 ...
4eh7: 650 pairs found
✅ Processing 4kip ...
4kip: 752 pairs found
✅ Processing 3nus ...
3nus: 271 pairs found
✅ Processing 6ep9 ...
6ep9: 923 pairs found
✅ Processing 3nuy ...
3nuy: 272 pairs found
✅ Processing 4w5j ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4w5j: 1680 pairs found
✅ Processing 1h1r ...
1h1r: 648 pairs found
✅ Processing 5eje ...
5eje: 1644 pairs found
✅ Processing 4jin ...
4jin: 459 pairs found
✅ Processing 5os1 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5os1: 594 pairs found
✅ Processing 4mf1 ...
4mf1: 604 pairs found
✅ Processing 3qtr ...
3qtr: 578 pairs found
✅ Processing 5j87 ...
5j87: 957 pairs found
✅ Processing 6ex0 ...
❌ Skipping 6ex0 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4cli ...
4cli: 642 pairs found
✅ Processing 5auy ...
5auy: 593 pairs found
✅ Processing 4wno ...
4wno: 588 pairs found
✅ Processing 3pp1 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
3pp1: 723 pairs found
✅ Processing 3zw3 ...
3zw3: 558 pairs found
✅ Processing 6cqf ...
6cqf: 636 pairs found
✅ Processing 2wxp ...
2wxp: 700 pairs found
✅ Processing 1m51 ...
1m51: 682 pairs found
✅ Processing 4a9r ...
4a9r: 550 pairs found
✅ Processing 4ocp ...
❌ Skipping 4ocp due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4yo6 ...
4yo6: 655 pairs found
✅ Processing 4kzc ...
4kzc: 637 pairs found
✅ Processing 1veb ...
1veb: 1031 pairs found
✅ Processing 4f08 ...
4f08: 457 pairs found
✅ Processing 5mhq ...
5mhq: 661 pairs found
✅ Processing 6s9w ...
6s9w: 988 pairs found
✅ Processing 2yer ...
2yer: 567 pairs found
✅ Processing 4rpv ...
4rpv: 668 pairs found
✅ Processing 1o4d ...
1o4d: 406 pairs found
✅ Processing 3vbw ...
3vbw: 308 pairs found
✅ Processing 4lop ...
4lop: 568 pairs found
✅ Processing 4nwm ...
4nwm: 899 pairs found
✅ Processing 4jps ...
4jps: 674 pairs found
✅ Processing 1a1b ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
1a1b: 624 pairs found
✅ Processing 2p3g ...
2p3g: 571 pairs found
✅ Processing 3zlw ...
3zlw: 435 pairs found
✅ Processing 3wyy ...
3wyy: 756 pairs found
✅ Processing 4nct ...
4nct: 725 pairs found
✅ Processing 5wo4 ...
5wo4: 676 pairs found
✅ Processing 4msu ...
4msu: 821 pairs found
✅ Processing 5ngb ...
5ngb: 622 pairs found
✅ Processing 4umq ...
4umq: 732 pairs found
✅ Processing 2xch ...
2xch: 641 pairs found
✅ Processing 5u6b ...
5u6b: 634 pairs found
✅ Processing 2ycf ...
2ycf: 729 pairs found
✅ Processing 3r7r ...
3r7r: 598 pairs found
✅ Processing 3ctq ...
3ctq: 1134 pairs found
✅ Processing 4q1c ...
4q1c: 746 pairs found
✅ Processing 4uzh ...
4uzh: 418 pairs found
✅ Processing 1kf0 ...
1kf0: 281 pairs found
✅ Processing 3q92 ...
3q92: 641 pairs found
✅ Processing 4axa ...
❌ Skipping 4axa due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4hnf ...

In [81]:
import os
print(os.getcwd())

/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial

Generating ECIF descriptors for external data

In [83]:
import os
import pandas as pd

protein_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/protein_split_pdb"
ligand_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/ligands_split_sdf_rdkit"

ligand_files = [f for f in os.listdir(ligand_dir) if f.endswith(".sdf")]
results = []

for ligand_file in ligand_files:
    prefix = ligand_file.split("_")[0]  # e.g., "1a1b"
    protein_file = os.path.join(protein_dir, f"{prefix}_protein_receptor.pdb")
    ligand_path = os.path.join(ligand_dir, ligand_file)

    if not os.path.exists(protein_file):
        print(f"⚠️ Protein file not found for {prefix}, skipping...")
        continue

    print(f"✅ Processing {prefix} ...")

    # === TRY-EXCEPT to skip any problematic complex ===
    try:
        ecif_vector = GetECIF(protein_file, ligand_path)
        if ecif_vector is None or len(ecif_vector) == 0:
            print(f"⚠️ Skipping {prefix} — no ECIF features generated.")
            continue
        # Add Complex ID as first column
        ecif_vector = [prefix] + ecif_vector
        results.append(ecif_vector)

    except Exception as e:
        print(f"❌ Skipping {prefix} due to error: {e}")
        continue

# Convert to DataFrame
if results:
    # First column = Complex_ID, rest = ECIF headers
    headers = ["Complex_ID"] + PossibleECIF
    df_ecif = pd.DataFrame(results, columns=headers)
    df_ecif.to_csv("ECIF_descriptors_test.csv", index=False)
    print(f"\n✅ ECIF descriptors saved to: ECIF_descriptors_train.csv")
else:
    print("❌ No ECIF features generated. Check your input files.")

✅ Processing 4CWF ...
4CWF: 418 pairs found
✅ Processing 6ZRC ...
6ZRC: 1451 pairs found
✅ Processing 1L5Q ...
1L5Q: 493 pairs found
✅ Processing 5RK9 ...
5RK9: 335 pairs found
✅ Processing 8CPH ...
8CPH: 500 pairs found
✅ Processing 4MGI ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4MGI: 581 pairs found
✅ Processing 7ER8 ...
7ER8: 1191 pairs found
✅ Processing 3FUR ...
3FUR: 753 pairs found
✅ Processing 8EYO ...
8EYO: 1026 pairs found
✅ Processing 5LO5 ...
5LO5: 829 pairs found
✅ Processing 6NWK ...
6NWK: 749 pairs found
✅ Processing 6B1U ...
6B1U: 798 pairs found
✅ Processing 3FXW ...
3FXW: 633 pairs found
✅ Processing 3NOX ...
3NOX: 592 pairs found
✅ Processing 4O76 ...
4O76: 641 pairs found
✅ Processing 7B31 ...
7B31: 896 pairs found
✅ Processing 5IAW ...
5IAW: 512 pairs found
✅ Processing 8U4W ...
8U4W: 975 pairs found
✅ Processing 3BGP ...
3BGP: 529 pairs found
✅ Processing 5TM6 ...
5TM6: 634 pairs found
✅ Processing 5P9J ...
5P9J: 784 pairs found
✅ Processing 4MGA ...
4MGA: 332 pairs found
✅ Processing 6JOJ ...
6JOJ: 704 pairs found
✅ Processing 7R4K ...
7R4K: 864 pairs found
✅ Processing 1O4I ...
1O4I: 517 pairs found
✅ Processing 3BF6 ...
3BF6: 741 pairs found
✅ Processing 3U2C ...
3U2C: 1520 pairs found
✅ Processing 7UBO ...
7UBO: 837 pairs found
✅ Processing 3W3K ...
3W3K: 437 pairs found
✅ Processing 6LX4 ...
❌ Skipping 6LX4 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 6YOJ ...
6YOJ: 914 pairs found
✅ Processing 4MG7 ...
4MG7: 583 pairs found
✅ Processing 6I2Y ...
6I2Y: 989 pairs found
✅ Processing 8A31 ...
8A31: 497 pairs found
✅ Processing 5N5N ...
5N5N: 765 pairs found
✅ Processing 5NK8 ...
5NK8: 729 pairs found
✅ Processing 6XRL ...
6XRL: 830 pairs found
✅ Processing 4L98 ...
4L98: 726 pairs found
✅ Processing 2ZIQ ...
2ZIQ: 696 pairs found
✅ Processing 3SMO ...
3SMO: 449 pairs found
✅ Processing 6WHA ...
6WHA: 487 pairs found
✅ Processing 4O75 ...
4O75: 475 pairs found
✅ Processing 3K65 ...
3K65: 105 pairs found
✅ Processing 3GWX ...
3GWX: 536 pairs found
✅ Processing 8A4N ...
❌ Skipping 8A4N due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5RK2 ...
5RK2: 376 pairs found
✅ Processing 9AS3 ...
9AS3: 561 pairs found
✅ Processing 5WIN ...
5WIN: 587 pairs found
✅ Processing 5J7F ...
5J7F: 882 pairs found
✅ Processing 4G9C ...
4G9C: 1044 pairs found
✅ Processing 2O64 ...
2O64: 540 pairs found
✅ Processing 7R9L ...
7R9L: 565 pairs found
✅ Processing 2RAK ...
2RAK: 365 pairs found
✅ Processing 7AW3 ...
7AW3: 587 pairs found
✅ Processing 5KRK ...
5KRK: 642 pairs found
✅ Processing 5TB6 ...
5TB6: 342 pairs found
✅ Processing 6YB8 ...
6YB8: 553 pairs found
✅ Processing 5LXD ...
5LXD: 608 pairs found
✅ Processing 6YV4 ...
6YV4: 408 pairs found
✅ Processing 4RC2 ...
4RC2: 545 pairs found
✅ Processing 5DXP ...
5DXP: 528 pairs found
✅ Processing 2QGT ...
2QGT: 577 pairs found
✅ Processing 2FLB ...
2FLB: 709 pairs found
✅ Processing 5R8K ...
5R8K: 232 pairs found
✅ Processing 1AZ2 ...
1AZ2: 1531 pairs found
✅ Processing 1X7J ...
1X7J: 553 pairs found
✅ Processing 7VUE ...
7VUE: 1028 pairs found
✅ Processing 2YKB ...
2YKB: 860 pairs found
✅ Processing 5MKR ...
5MKR: 716 pairs found
✅ Processing 7R9W ...
7R9W: 311 pairs found
✅ Processing 6PKC ...
6PKC: 877 pairs found
✅ Processing 7ZLR ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7ZLR: 713 pairs found
✅ Processing 4D9T ...
4D9T: 596 pairs found
✅ Processing 3V2Y ...
❌ Skipping 3V2Y due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 6DXL ...
6DXL: 811 pairs found
✅ Processing 1T4U ...
1T4U: 702 pairs found
✅ Processing 2XQK ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
2XQK: 175 pairs found
✅ Processing 7G14 ...
7G14: 632 pairs found
✅ Processing 5DEY ...
5DEY: 684 pairs found
✅ Processing 7CKF ...
7CKF: 843 pairs found
✅ Processing 4OJ4 ...
4OJ4: 396 pairs found
✅ Processing 4AW5 ...
4AW5: 716 pairs found
✅ Processing 7RLF ...
7RLF: 748 pairs found
✅ Processing 5TOE ...
5TOE: 465 pairs found
✅ Processing 8DU9 ...
8DU9: 847 pairs found
✅ Processing 5AP3 ...
5AP3: 598 pairs found
✅ Processing 5JZY ...
5JZY: 778 pairs found
✅ Processing 4ZN9 ...
4ZN9: 796 pairs found
✅ Processing 6A6P ...
6A6P: 738 pairs found
✅ Processing 8V6Y ...
8V6Y: 448 pairs found
✅ Processing 3NOA ...
3NOA: 1022 pairs found
✅ Processing 6NJS ...
6NJS: 866 pairs found
✅ Processing 6HCY ...
6HCY: 1039 pairs found
✅ Processing 9CHU ...
9CHU: 291 pairs found
✅ Processing 4LXA ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4LXA: 942 pairs found
✅ Processing 6DFM ...
6DFM: 584 pairs found
✅ Processing 8SS6 ...
8SS6: 753 pairs found
✅ Processing 8EV1 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
8EV1: 575 pairs found
✅ Processing 3RTP ...
3RTP: 578 pairs found
✅ Processing 4FMC ...
4FMC: 860 pairs found
✅ Processing 4OH6 ...
❌ Skipping 4OH6 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3QCE ...
3QCE: 835 pairs found
✅ Processing 6DW3 ...
6DW3: 707 pairs found
✅ Processing 1O45 ...
1O45: 777 pairs found
✅ Processing 6KHE ...
6KHE: 572 pairs found
✅ Processing 5XMX ...
5XMX: 836 pairs found
✅ Processing 8CSU ...
❌ Skipping 8CSU due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 6BMU ...
6BMU: 710 pairs found
✅ Processing 5S96 ...
5S96: 337 pairs found
✅ Processing 8GZ3 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
8GZ3: 1044 pairs found
✅ Processing 5S8Y ...
5S8Y: 565 pairs found
✅ Processing 4BI1 ...
4BI1: 291 pairs found
✅ Processing 1NM6 ...
1NM6: 817 pairs found
✅ Processing 4FA6 ...
4FA6: 538 pairs found
✅ Processing 8IMX ...
8IMX: 57 pairs found
✅ Processing 1TOM ...
1TOM: 659 pairs found
✅ Processing 7RUZ ...
7RUZ: 451 pairs found
✅ Processing 4KBC ...
4KBC: 510 pairs found
✅ Processing 5TM5 ...
5TM5: 591 pairs found
✅ Processing 5DH3 ...
5DH3: 685 pairs found
✅ Processing 3IMX ...
3IMX: 477 pairs found
✅ Processing 4XVE ...
4XVE: 1343 pairs found
✅ Processing 6C5Q ...
❌ Skipping 6C5Q due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 7DBK ...
7DBK: 1146 pairs found
✅ Processing 8TU9 ...
8TU9: 910 pairs found
✅ Processing 7MRC ...
7MRC: 1664 pairs found
✅ Processing 5TB5 ...
5TB5: 1276 pairs found
✅ Processing 3FT5 ...
3FT5: 291 pairs found
✅ Processing 7X9D ...
7X9D: 434 pairs found
✅ Processing 4CIK ...
4CIK: 422 pairs found
✅ Processing 7FT7 ...
7FT7: 293 pairs found
✅ Processing 5WS0 ...
5WS0: 550 pairs found
✅ Processing 3CLD ...
3CLD: 934 pairs found
✅ Processing 7FV2 ...
7FV2: 521 pairs found
✅ Processing 7M44 ...
7M44: 640 pairs found
✅ Processing 5MVC ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5MVC: 919 pairs found
✅ Processing 4USE ...
4USE: 573 pairs found
✅ Processing 4PYX ...
4PYX: 653 pairs found
✅ Processing 7BGQ ...
7BGQ: 531 pairs found
✅ Processing 3H0W ...
3H0W: 193 pairs found
✅ Processing 7WGP ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7WGP: 586 pairs found
✅ Processing 3ELA ...
3ELA: 244 pairs found
✅ Processing 4C67 ...
4C67: 387 pairs found
✅ Processing 5VD1 ...
5VD1: 723 pairs found
✅ Processing 5XGN ...
5XGN: 625 pairs found
✅ Processing 5UGB ...
5UGB: 550 pairs found
✅ Processing 3TTJ ...
3TTJ: 739 pairs found
✅ Processing 2Y48 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
2Y48: 1790 pairs found
✅ Processing 4EY6 ...
4EY6: 40 pairs found
✅ Processing 4G9R ...
4G9R: 914 pairs found
✅ Processing 5QIE ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5QIE: 1005 pairs found
✅ Processing 6ZC9 ...
6ZC9: 332 pairs found
✅ Processing 7FQL ...
7FQL: 878 pairs found
✅ Processing 4CWN ...
4CWN: 548 pairs found
✅ Processing 4ODR ...
4ODR: 658 pairs found
✅ Processing 5TKD ...
5TKD: 569 pairs found
✅ Processing 5RKL ...
5RKL: 419 pairs found
✅ Processing 7WMM ...
7WMM: 415 pairs found
✅ Processing 7WNV ...
7WNV: 799 pairs found
✅ Processing 5VD5 ...
5VD5: 795 pairs found
✅ Processing 4NGA ...
4NGA: 1027 pairs found
✅ Processing 4IM2 ...
4IM2: 763 pairs found
✅ Processing 7FVE ...
7FVE: 623 pairs found
✅ Processing 8YP5 ...
8YP5: 580 pairs found
✅ Processing 6TFV ...
6TFV: 969 pairs found
✅ Processing 3DT3 ...
3DT3: 622 pairs found
✅ Processing 5U3U ...
5U3U: 895 pairs found
✅ Processing 7EVJ ...
7EVJ: 580 pairs found
✅ Processing 3ZXT ...
3ZXT: 643 pairs found
✅ Processing 3ZLO ...
3ZLO: 1044 pairs found
✅ Processing 5IN5 ...
5IN5: 1384 pairs found
✅ Processing 4BQG ...
4BQG: 433 pairs found
✅ Processing 1Q3F ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
1Q3F: 304 pairs found
✅ Processing 1DWD ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
1DWD: 732 pairs found
✅ Processing 2C6E ...
2C6E: 879 pairs found
✅ Processing 9JD4 ...
9JD4: 300 pairs found
✅ Processing 3FMJ ...
3FMJ: 445 pairs found
✅ Processing 7ZXB ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7ZXB: 569 pairs found
✅ Processing 4APD ...
4APD: 284 pairs found
✅ Processing 8T4M ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
8T4M: 641 pairs found
✅ Processing 5NMM ...
5NMM: 241 pairs found
✅ Processing 1WOK ...
1WOK: 544 pairs found
✅ Processing 5L2Y ...
5L2Y: 1103 pairs found
✅ Processing 5WUK ...
5WUK: 662 pairs found
✅ Processing 4IZY ...
4IZY: 654 pairs found
✅ Processing 3M4H ...
3M4H: 1562 pairs found
✅ Processing 6X83 ...
6X83: 445 pairs found
✅ Processing 1EVR ...
1EVR: 263 pairs found
✅ Processing 6QZR ...
6QZR: 294 pairs found
✅ Processing 7VNQ ...
7VNQ: 419 pairs found
✅ Processing 7QJU ...
7QJU: 822 pairs found
✅ Processing 1M49 ...
1M49: 747 pairs found
✅ Processing 3LQ3 ...
❌ Skipping 3LQ3 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3F66 ...
3F66: 595 pairs found
✅ Processing 1GIH ...
1GIH: 589 pairs found
✅ Processing 7CBX ...
7CBX: 667 pairs found
✅ Processing 5QIX ...
5QIX: 324 pairs found
✅ Processing 7P3B ...
7P3B: 778 pairs found
✅ Processing 7FV1 ...
7FV1: 651 pairs found
✅ Processing 4KCG ...
4KCG: 775 pairs found
✅ Processing 5AAB ...
5AAB: 596 pairs found
✅ Processing 5IZQ ...
5IZQ: 929 pairs found
✅ Processing 8JTT ...
8JTT: 151 pairs found
✅ Processing 7VNR ...
7VNR: 419 pairs found
✅ Processing 6KXY ...
6KXY: 686 pairs found
✅ Processing 1T65 ...
1T65: 545 pairs found
✅ Processing 5HM0 ...
5HM0: 425 pairs found
✅ Processing 6TR5 ...
6TR5: 285 pairs found
✅ Processing 1KTS ...
1KTS: 914 pairs found
✅ Processing 4QFZ ...
4QFZ: 582 pairs found
✅ Processing 2QZO ...
2QZO: 655 pairs found
✅ Processing 6T2D ...
6T2D: 187 pairs found
✅ Processing 6SNW ...
6SNW: 590 pairs found
✅ Processing 2JG4 ...
2JG4: 101 pairs found
✅ Processing 6H22 ...
6H22: 325 pairs found
✅ Processing 7AAZ ...
7AAZ: 1182 pairs found
✅ Processing 5Q0J ...
5Q0J: 883 pairs found
✅ Processing 4FSM ...
4FSM: 570 pairs found
✅ Processing 4ODE ...
4ODE: 872 pairs found
✅ Processing 7EM5 ...
7EM5: 367 pairs found
✅ Processing 5DRM ...
5DRM: 575 pairs found
✅ Processing 8U2E ...
8U2E: 642 pairs found
✅ Processing 2Q8I ...
2Q8I: 505 pairs found
✅ Processing 8OKU ...
8OKU: 758 pairs found
✅ Processing 5IA3 ...
5IA3: 673 pairs found
✅ Processing 7AVX ...
7AVX: 895 pairs found
✅ Processing 8J61 ...
8J61: 1118 pairs found
✅ Processing 6TW2 ...
6TW2: 583 pairs found
✅ Processing 5S80 ...
5S80: 744 pairs found
✅ Processing 5KR9 ...
5KR9: 529 pairs found
✅ Processing 7M0K ...
7M0K: 668 pairs found
✅ Processing 7EZF ...
7EZF: 526 pairs found
✅ Processing 5Z8Z ...
5Z8Z: 438 pairs found
✅ Processing 5UC4 ...
5UC4: 539 pairs found
✅ Processing 5DDB ...
5DDB: 652 pairs found
✅ Processing 4C4I ...
4C4I: 664 pairs found
✅ Processing 4RBL ...
4RBL: 475 pairs found
✅ Processing 6DHC ...
6DHC: 1047 pairs found
✅ Processing 4J6I ...
4J6I: 768 pairs found
✅ Processing 4ZN7 ...
4ZN7: 524 pairs found
✅ Processing 4MGD ...
4MGD: 483 pairs found
✅ Processing 6LG8 ...
6LG8: 339 pairs found
✅ Processing 3QUE ...
3QUE: 725 pairs found
✅ Processing 7M45 ...
7M45: 238 pairs found
✅ Processing 8P77 ...
8P77: 569 pairs found
✅ Processing 1YPM ...
❌ Skipping 1YPM due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3CGF ...
3CGF: 479 pairs found
✅ Processing 3Q4T ...
3Q4T: 611 pairs found
✅ Processing 7A2H ...
7A2H: 274 pairs found
✅ Processing 6TI8 ...
6TI8: 761 pairs found
✅ Processing 7G87 ...
7G87: 168 pairs found
✅ Processing 7R9T ...
7R9T: 673 pairs found
✅ Processing 5KOT ...
5KOT: 905 pairs found
✅ Processing 5SCJ ...
5SCJ: 702 pairs found
✅ Processing 5IA0 ...
5IA0: 663 pairs found
✅ Processing 4OAS ...
4OAS: 701 pairs found
✅ Processing 4U43 ...
4U43: 450 pairs found
✅ Processing 5BUE ...
5BUE: 700 pairs found
✅ Processing 4BAO ...
4BAO: 850 pairs found
✅ Processing 5KPM ...
5KPM: 485 pairs found
✅ Processing 5QDE ...
❌ Skipping 5QDE due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 9L3T ...
9L3T: 461 pairs found
✅ Processing 5GTY ...
5GTY: 943 pairs found
✅ Processing 1ND5 ...
1ND5: 515 pairs found
✅ Processing 4JV9 ...
4JV9: 524 pairs found
✅ Processing 7MIG ...
7MIG: 864 pairs found
✅ Processing 8P70 ...
8P70: 507 pairs found
✅ Processing 4EZ3 ...
4EZ3: 528 pairs found
✅ Processing 5TYV ...
5TYV: 582 pairs found
✅ Processing 8DZQ ...
8DZQ: 556 pairs found
✅ Processing 3O64 ...
3O64: 904 pairs found
✅ Processing 6YLL ...
6YLL: 521 pairs found
✅ Processing 8A9G ...
8A9G: 237 pairs found
✅ Processing 5UU1 ...
5UU1: 704 pairs found
✅ Processing 4XXS ...
4XXS: 538 pairs found
✅ Processing 3V9T ...
3V9T: 826 pairs found
✅ Processing 4XUC ...
4XUC: 419 pairs found
✅ Processing 2CDZ ...
2CDZ: 574 pairs found
✅ Processing 9CHX ...
9CHX: 500 pairs found
✅ Processing 6O8C ...
6O8C: 766 pairs found
✅ Processing 7VFU ...
7VFU: 191 pairs found
✅ Processing 4KIO ...
4KIO: 737 pairs found
✅ Processing 6N9P ...
6N9P: 761 pairs found
✅ Processing 3DDQ ...
3DDQ: 608 pairs found
✅ Processing 6S1B ...
6S1B: 441 pairs found
✅ Processing 3L1B ...
3L1B: 866 pairs found
✅ Processing 8CQL ...
8CQL: 841 pairs found
✅ Processing 2BAK ...
2BAK: 980 pairs found
✅ Processing 6I3S ...
6I3S: 592 pairs found
✅ Processing 3AM7 ...
❌ Skipping 3AM7 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 5RK6 ...
5RK6: 498 pairs found
✅ Processing 7LTT ...
7LTT: 597 pairs found
✅ Processing 4LWE ...
4LWE: 561 pairs found
✅ Processing 7HBU ...
❌ Skipping 7HBU due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3X0A ...
3X0A: 378 pairs found
✅ Processing 7UL3 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7UL3: 471 pairs found
✅ Processing 5JWL ...
5JWL: 172 pairs found
✅ Processing 8Q6G ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
8Q6G: 715 pairs found
✅ Processing 8DUB ...
8DUB: 819 pairs found
✅ Processing 6YXI ...
6YXI: 513 pairs found
✅ Processing 6MWR ...
6MWR: 662 pairs found
✅ Processing 2IO6 ...
2IO6: 743 pairs found
✅ Processing 8RBC ...
8RBC: 341 pairs found
✅ Processing 5LS1 ...
5LS1: 659 pairs found
✅ Processing 4QMW ...
4QMW: 536 pairs found
✅ Processing 3DZY ...
3DZY: 541 pairs found
✅ Processing 6YEA ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
6YEA: 572 pairs found
✅ Processing 7U8V ...
7U8V: 203 pairs found
✅ Processing 3EAX ...
3EAX: 438 pairs found
✅ Processing 6X3Y ...
6X3Y: 490 pairs found
✅ Processing 5KRC ...
5KRC: 580 pairs found
✅ Processing 7L9A ...
7L9A: 780 pairs found
✅ Processing 4FCR ...
4FCR: 621 pairs found
✅ Processing 6XD3 ...
6XD3: 665 pairs found
✅ Processing 5Q0R ...
5Q0R: 1107 pairs found
✅ Processing 4GZM ...
4GZM: 862 pairs found
✅ Processing 6PNX ...
6PNX: 440 pairs found
✅ Processing 4ZWE ...
4ZWE: 711 pairs found
✅ Processing 5L30 ...
5L30: 1081 pairs found
✅ Processing 1YXX ...
1YXX: 415 pairs found
✅ Processing 7QK4 ...
7QK4: 881 pairs found
✅ Processing 8J5W ...
8J5W: 1166 pairs found
✅ Processing 5RJU ...
5RJU: 246 pairs found
✅ Processing 3G6Z ...
3G6Z: 849 pairs found
✅ Processing 6QG7 ...
6QG7: 553 pairs found
✅ Processing 8GMD ...
8GMD: 687 pairs found
✅ Processing 5X5O ...
5X5O: 934 pairs found
✅ Processing 4UYA ...
4UYA: 463 pairs found
✅ Processing 6JX0 ...
6JX0: 694 pairs found
✅ Processing 7KVZ ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7KVZ: 600 pairs found
✅ Processing 3BEG ...
3BEG: 518 pairs found
✅ Processing 8VO4 ...
8VO4: 744 pairs found
✅ Processing 9BCV ...
9BCV: 490 pairs found
✅ Processing 5FQV ...
5FQV: 696 pairs found
✅ Processing 2WTV ...
2WTV: 746 pairs found
✅ Processing 8C13 ...
8C13: 761 pairs found
✅ Processing 1LQ8 ...
1LQ8: 2 pairs found
✅ Processing 8QHQ ...
8QHQ: 699 pairs found
✅ Processing 5ED1 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5ED1: 452 pairs found
✅ Processing 5TLG ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5TLG: 590 pairs found
✅ Processing 6QY9 ...
6QY9: 822 pairs found
✅ Processing 5DEU ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5DEU: 489 pairs found
✅ Processing 3OAW ...
3OAW: 539 pairs found
✅ Processing 1AWF ...
1AWF: 908 pairs found
✅ Processing 4ANS ...
4ANS: 568 pairs found
✅ Processing 7D6Y ...
❌ Skipping 7D6Y due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4XBM ...
4XBM: 138 pairs found
✅ Processing 2Q8S ...
2Q8S: 757 pairs found
✅ Processing 3QGY ...
3QGY: 598 pairs found
✅ Processing 7AW0 ...
7AW0: 538 pairs found
✅ Processing 8CSG ...
8CSG: 364 pairs found
✅ Processing 3QTF ...
3QTF: 651 pairs found
✅ Processing 5KHM ...
5KHM: 736 pairs found
✅ Processing 7HBL ...
7HBL: 268 pairs found
✅ Processing 2AX7 ...
❌ Skipping 2AX7 due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 3R00 ...
3R00: 345 pairs found
✅ Processing 4PPC ...
4PPC: 687 pairs found
✅ Processing 5S7Q ...
5S7Q: 732 pairs found
✅ Processing 6FRF ...
6FRF: 561 pairs found
✅ Processing 5M56 ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5M56: 668 pairs found
✅ Processing 3C0G ...
3C0G: 448 pairs found
✅ Processing 6I29 ...
6I29: 609 pairs found
✅ Processing 7KTB ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
7KTB: 1005 pairs found
✅ Processing 5FTG ...
❌ Skipping 5FTG due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 7T4V ...
7T4V: 636 pairs found
✅ Processing 7MDP ...
7MDP: 441 pairs found
✅ Processing 6VQM ...
6VQM: 655 pairs found
✅ Processing 8PO1 ...
8PO1: 1003 pairs found
✅ Processing 5ZYJ ...
5ZYJ: 684 pairs found
✅ Processing 4YKT ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
4YKT: 547 pairs found
✅ Processing 6TEZ ...
6TEZ: 818 pairs found
✅ Processing 7M05 ...
7M05: 499 pairs found
✅ Processing 6N0Q ...
6N0Q: 811 pairs found
✅ Processing 8TSA ...
8TSA: 649 pairs found
✅ Processing 8XB1 ...
8XB1: 541 pairs found
✅ Processing 7XZH ...
❌ Skipping 7XZH due to error: 'NoneType' object has no attribute 'UpdatePropertyCache'
✅ Processing 4OD9 ...
4OD9: 817 pairs found
✅ Processing 5QIF ...
WARNING: Ligand contains unsupported atom types. Only supported atom-type pairs are counted.
5QIF: 994 pairs found
✅ Processing 4EGI ...

Joining Target label pIC to the training descriptors

In [86]:
import pandas as pd

# Load ECIF descriptors
df_ecif = pd.read_csv("ECIF_descriptors_train.csv")  # Contains Complex_ID + ECIF descriptors

# Load activity data
df_activity = pd.read_csv("general_activity_2483.csv")  # Contains PDB_ID and pIC

# Map pIC to ECIF dataframe based on Complex_ID
df_ecif["pIC"] = df_ecif["Complex_ID"].map(df_activity.set_index("PDB_ID")["pIC"])

# Save the merged file
df_ecif.to_csv("ECIF_with_activity_train.csv", index=False)
print("✅ ECIF descriptors with pIC added as last column saved to 'ECIF_with_activity_train.csv'")

✅ ECIF descriptors with pIC added as last column saved to 'ECIF_with_activity_train.csv'

In [88]:
df_ecif.head()

,Complex_ID,C;4;1;3;0;0-Br;1;1;0;0;0,C;4;1;3;0;0-C;3;3;0;1;1,C;4;1;3;0;0-C;4;1;1;0;0,C;4;1;3;0;0-C;4;1;2;0;0,C;4;1;3;0;0-C;4;1;3;0;0,C;4;1;3;0;0-C;4;2;0;0;0,C;4;1;3;0;0-C;4;2;1;0;0,C;4;1;3;0;0-C;4;2;1;0;1,C;4;1;3;0;0-C;4;2;1;1;1,...,S;2;2;0;0;0-S;2;2;0;0;0,S;2;2;0;0;0-S;2;2;0;0;1,S;2;2;0;0;0-S;2;2;0;1;1,S;2;2;0;0;0-S;3;3;0;0;0,S;2;2;0;0;0-S;3;3;0;0;1,S;2;2;0;0;0-S;4;3;0;0;0,S;2;2;0;0;0-S;6;4;0;0;0,S;2;2;0;0;0-S;6;4;0;0;1,S;2;2;0;0;0-S;7;4;0;0;0,pIC
0,3r02,8,0,0,0,0,0,0,27,0,...,0,0,0,0,0,0,0,0,0,9.00
1,6c2t,0,0,0,0,0,0,0,47,0,...,0,0,0,0,0,0,0,0,0,9.05
2,5t31,0,0,0,0,8,0,0,20,0,...,0,0,0,0,0,0,0,0,0,6.96
3,4eop,0,0,0,0,0,0,8,49,0,...,0,0,0,0,0,0,0,0,0,6.05
4,2ghg,0,0,0,0,0,0,6,38,0,...,0,0,0,0,0,0,0,0,0,8.82

Generating RDKit descriptors for training dataset

In [16]:
from rdkit import Chem
from rdkit.ML.Descriptors import MoleculeDescriptors
from rdkit.Chem import Descriptors
import pandas as pd
import os
from tqdm import tqdm

# Define directories
ligand_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/ligand_train_rdkit"
save_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_train.csv"

# List all ligand files
ligand_files = [f for f in os.listdir(ligand_dir) if f.endswith('.sdf') or f.endswith('.mol')]

# Get list of RDKit descriptors
descriptor_names = [desc[0] for desc in Descriptors._descList]
calculator = MoleculeDescriptors.MolecularDescriptorCalculator(descriptor_names)

# Storage list
data = []

# Loop through ligands
for file in tqdm(ligand_files, desc="Calculating RDKit descriptors"):
    file_path = os.path.join(ligand_dir, file)
    mol = Chem.MolFromMolFile(file_path)
    
    if mol is None:
        print(f"⚠️ Skipping {file} (cannot read molecule)")
        continue
    
    # Calculate all RDKit descriptors
    desc_values = calculator.CalcDescriptors(mol)
    
    # Append results
    complex_id = os.path.splitext(file)[0]  # use filename as Complex_ID
    data.append([complex_id] + list(desc_values))

# Create DataFrame
desc_df = pd.DataFrame(data, columns=["Complex_ID"] + descriptor_names)

# Save to CSV
desc_df.to_csv(save_path, index=False)
print(f"RDKit descriptors saved successfully at:\n{save_path}")

Calculating RDKit descriptors:   3%|▎         | 70/2401 [00:00<00:26, 86.56it/s]

⚠️ Skipping 2wd1_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   4%|▎        | 100/2401 [00:01<00:25, 90.17it/s]

⚠️ Skipping 2c69_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2w1e_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   5%|▍        | 130/2401 [00:01<00:25, 90.70it/s]

⚠️ Skipping 4enx_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2yoh_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   7%|▋        | 170/2401 [00:02<00:24, 90.83it/s]

⚠️ Skipping 2yir_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   8%|▋        | 199/2401 [00:02<00:25, 87.69it/s]

⚠️ Skipping 5ghv_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4yur_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  12%|█        | 287/2401 [00:03<00:23, 91.73it/s]

⚠️ Skipping 1q3w_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5j5x_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  15%|█▎       | 349/2401 [00:04<00:22, 89.50it/s]

⚠️ Skipping 2w1c_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  16%|█▍       | 380/2401 [00:04<00:21, 92.12it/s]

⚠️ Skipping 6ex0_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4ocp_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  17%|█▌       | 420/2401 [00:05<00:21, 92.24it/s]

⚠️ Skipping 4axa_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5bmm_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  19%|█▋       | 459/2401 [00:05<00:21, 88.58it/s]

⚠️ Skipping 3qtx_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4e6c_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  20%|█▊       | 488/2401 [00:05<00:21, 90.60it/s]

⚠️ Skipping 2ycq_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  22%|█▉       | 518/2401 [00:06<00:21, 89.01it/s]

⚠️ Skipping 5t1t_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  23%|██       | 556/2401 [00:06<00:22, 83.81it/s]

⚠️ Skipping 2x6i_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  24%|██▏      | 577/2401 [00:06<00:20, 87.59it/s]

⚠️ Skipping 5dhs_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5a54_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  32%|██▌     | 769/2401 [00:08<00:13, 117.99it/s]

⚠️ Skipping 2xk9_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  33%|███      | 801/2401 [00:08<00:18, 88.66it/s]

⚠️ Skipping 5l2w_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  36%|███▏     | 862/2401 [00:09<00:16, 93.71it/s]

⚠️ Skipping 3hrb_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  37%|██▉     | 890/2401 [00:09<00:13, 113.82it/s]

⚠️ Skipping 3mw1_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2c4g_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1w2h_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3feg_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5m4i_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  41%|███▎    | 986/2401 [00:10<00:13, 107.04it/s]

⚠️ Skipping 3o0g_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  44%|███    | 1046/2401 [00:11<00:13, 101.44it/s]

⚠️ Skipping 2hiw_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  46%|███▏   | 1098/2401 [00:11<00:11, 115.17it/s]

⚠️ Skipping 1nlo_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  48%|███▍   | 1159/2401 [00:12<00:12, 101.13it/s]

⚠️ Skipping 2wev_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  54%|███▊   | 1293/2401 [00:13<00:09, 114.75it/s]

⚠️ Skipping 4aua_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3r8v_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5dhr_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  54%|███▊   | 1307/2401 [00:13<00:09, 120.71it/s]

⚠️ Skipping 5jt2_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  58%|████   | 1400/2401 [00:14<00:09, 106.06it/s]

⚠️ Skipping 3le6_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2xba_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  60%|████▏  | 1437/2401 [00:15<00:08, 113.33it/s]

⚠️ Skipping 2c5x_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  64%|████▌  | 1547/2401 [00:16<00:08, 105.47it/s]

⚠️ Skipping 3qxp_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4v05_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  66%|████▌  | 1583/2401 [00:16<00:07, 112.93it/s]

⚠️ Skipping 1a08_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  69%|████▊  | 1656/2401 [00:17<00:06, 115.44it/s]

⚠️ Skipping 6gn1_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  77%|█████▍ | 1846/2401 [00:18<00:04, 121.45it/s]

⚠️ Skipping 5w6o_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2xh5_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  78%|█████▍ | 1884/2401 [00:19<00:04, 117.33it/s]

⚠️ Skipping 2x81_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2w7x_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  83%|█████▊ | 1981/2401 [00:20<00:03, 106.30it/s]

⚠️ Skipping 4bda_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4xv1_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  84%|█████▊ | 2005/2401 [00:20<00:03, 111.22it/s]

⚠️ Skipping 2x6f_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4uj9_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2c5y_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  87%|██████▉ | 2078/2401 [00:21<00:03, 92.69it/s]

⚠️ Skipping 2w1g_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5dht_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3vap_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  90%|███████▏| 2164/2401 [00:22<00:02, 98.44it/s]

⚠️ Skipping 6es0_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4gcj_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  97%|███████▋| 2318/2401 [00:23<00:01, 79.72it/s]

⚠️ Skipping 1bux_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  97%|███████▊| 2340/2401 [00:23<00:00, 85.16it/s]

⚠️ Skipping 6q8p_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  98%|███████▊| 2363/2401 [00:24<00:00, 97.29it/s]

⚠️ Skipping 3r9n_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  99%|██████▉| 2386/2401 [00:24<00:00, 100.94it/s]

⚠️ Skipping 5wjj_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors: 100%|████████| 2401/2401 [00:24<00:00, 97.74it/s]

⚠️ Skipping 3hv5_ligand_rdkit.sdf (cannot read molecule)
✅ RDKit descriptors saved successfully at:
/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_train.csv

Generating RDKit descriptors for external dataset

In [17]:
from rdkit import Chem
from rdkit.ML.Descriptors import MoleculeDescriptors
from rdkit.Chem import Descriptors
import pandas as pd
import os
from tqdm import tqdm

# Define directories
ligand_dir = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/ligands_split_sdf_rdkit"
save_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_test.csv"

# List all ligand files
ligand_files = [f for f in os.listdir(ligand_dir) if f.endswith('.sdf') or f.endswith('.mol')]

# Get list of RDKit descriptors
descriptor_names = [desc[0] for desc in Descriptors._descList]
calculator = MoleculeDescriptors.MolecularDescriptorCalculator(descriptor_names)

# Storage list
data = []

# Loop through ligands
for file in tqdm(ligand_files, desc="Calculating RDKit descriptors"):
    file_path = os.path.join(ligand_dir, file)
    mol = Chem.MolFromMolFile(file_path)
    
    if mol is None:
        print(f"⚠️ Skipping {file} (cannot read molecule)")
        continue
    
    # Calculate all RDKit descriptors
    desc_values = calculator.CalcDescriptors(mol)
    
    # Append results
    complex_id = os.path.splitext(file)[0]  # use filename as Complex_ID
    data.append([complex_id] + list(desc_values))

# Create DataFrame
desc_df = pd.DataFrame(data, columns=["Complex_ID"] + descriptor_names)

# Save to CSV
desc_df.to_csv(save_path, index=False)
print(f"✅ RDKit descriptors saved successfully at:\n{save_path}")

Calculating RDKit descriptors:   1%|          | 37/6340 [00:00<01:48, 58.35it/s]

⚠️ Skipping 6LX4_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8A4N_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   1%|▏         | 85/6340 [00:01<01:18, 79.36it/s]

⚠️ Skipping 3V2Y_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   2%|▏        | 114/6340 [00:01<01:13, 84.24it/s]

⚠️ Skipping 4OH6_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8CSU_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   2%|▏        | 132/6340 [00:01<01:26, 71.86it/s]

⚠️ Skipping 6C5Q_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   3%|▏        | 170/6340 [00:02<01:18, 78.62it/s][17:09:05] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:05] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:   3%|▎        | 210/6340 [00:02<01:08, 90.09it/s]

⚠️ Skipping 3LQ3_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   4%|▎        | 262/6340 [00:03<01:03, 96.44it/s]

⚠️ Skipping 1YPM_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5QDE_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   5%|▍       | 306/6340 [00:03<00:57, 105.81it/s]

⚠️ Skipping 3AM7_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7HBU_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   6%|▍       | 362/6340 [00:04<00:56, 106.40it/s]

⚠️ Skipping 7D6Y_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2AX7_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   6%|▌        | 373/6340 [00:04<01:13, 81.44it/s]

⚠️ Skipping 5FTG_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7XZH_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   7%|▌        | 415/6340 [00:05<01:03, 93.30it/s]

⚠️ Skipping 8A2I_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5NUD_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   7%|▌       | 450/6340 [00:05<00:56, 104.11it/s]

⚠️ Skipping 6YWA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   8%|▌       | 488/6340 [00:05<00:53, 110.13it/s]

⚠️ Skipping 3F2R_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   8%|▋       | 514/6340 [00:06<00:49, 117.52it/s]

⚠️ Skipping 6N55_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:   9%|▊        | 588/6340 [00:06<00:57, 99.87it/s]

⚠️ Skipping 4GHI_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  10%|▊       | 614/6340 [00:07<00:52, 109.94it/s]

⚠️ Skipping 4OH5_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8Y58_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  10%|▊       | 628/6340 [00:07<00:48, 117.20it/s]

⚠️ Skipping 7X9Q_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  10%|▊       | 655/6340 [00:07<00:52, 107.74it/s]

⚠️ Skipping 6UVG_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5NFP_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  11%|▊       | 691/6340 [00:07<00:50, 112.78it/s]

⚠️ Skipping 4FLP_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7BYN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3FEG_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  12%|▉       | 765/6340 [00:08<00:47, 116.43it/s]

⚠️ Skipping 7WLK_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  12%|█        | 790/6340 [00:08<00:59, 93.07it/s]

⚠️ Skipping 1YPG_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4CG9_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4OJ9_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  13%|█       | 817/6340 [00:08<00:51, 106.69it/s]

⚠️ Skipping 8FE9_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  14%|█       | 879/6340 [00:09<00:49, 110.72it/s]

⚠️ Skipping 7PU9_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8T1E_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8CSP_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  15%|█▏      | 922/6340 [00:09<00:44, 122.62it/s]

⚠️ Skipping 6C1I_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8SSA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  15%|█▏      | 950/6340 [00:10<00:46, 117.08it/s]

⚠️ Skipping 1PK2_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4XJJ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2O1Y_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  15%|█▏      | 974/6340 [00:10<00:49, 108.82it/s][17:09:13] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:13] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  16%|█      | 1006/6340 [00:10<00:42, 126.06it/s]

⚠️ Skipping 7BMB_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5OGC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6LXC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5DSH_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  16%|█▏     | 1019/6340 [00:10<00:51, 103.33it/s]

⚠️ Skipping 7QY2_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  17%|█▎      | 1066/6340 [00:11<00:55, 94.56it/s]

⚠️ Skipping 7QY0_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6LXB_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  17%|█▏     | 1091/6340 [00:11<00:49, 105.74it/s]

⚠️ Skipping 6UVD_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  18%|█▏     | 1115/6340 [00:11<00:51, 100.69it/s]

⚠️ Skipping 4QBX_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8A2H_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  19%|█▎     | 1189/6340 [00:12<00:51, 100.81it/s]

⚠️ Skipping 6XUM_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5V56_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  19%|█▎     | 1227/6340 [00:12<00:48, 105.39it/s]

⚠️ Skipping 4MSL_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8BHB_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  20%|█▎     | 1238/6340 [00:13<00:50, 101.17it/s]

⚠️ Skipping 3B67_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2C8Y_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  20%|█▌      | 1278/6340 [00:13<00:56, 89.29it/s]

⚠️ Skipping 7O6K_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  20%|█▋      | 1299/6340 [00:13<00:52, 96.47it/s]

⚠️ Skipping 6C3E_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2CHX_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  21%|█▋      | 1319/6340 [00:14<01:04, 78.20it/s]

⚠️ Skipping 6ZWO_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8X7B_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8DU8_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8G1E_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2C8X_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  21%|█▋      | 1353/6340 [00:14<00:52, 94.11it/s]

⚠️ Skipping 8E0F_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6YDZ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  22%|█▋      | 1375/6340 [00:14<00:52, 94.59it/s]

⚠️ Skipping 6CLZ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  22%|█▊      | 1404/6340 [00:15<01:03, 77.72it/s]

⚠️ Skipping 1YSI_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8CNF_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  22%|█▊      | 1425/6340 [00:15<01:05, 74.57it/s]

⚠️ Skipping 1Q3W_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  24%|█▉      | 1500/6340 [00:16<01:00, 80.18it/s]

⚠️ Skipping 8FDV_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  24%|█▉      | 1522/6340 [00:16<00:52, 91.61it/s]

⚠️ Skipping 8SZH_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1B2I_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6O0P_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8TBI_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  25%|█▋     | 1559/6340 [00:16<00:44, 108.44it/s]

⚠️ Skipping 5WLQ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8SOS_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6TL3_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  25%|█▋     | 1570/6340 [00:16<00:45, 103.91it/s]

⚠️ Skipping 6L38_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  25%|██      | 1602/6340 [00:17<00:48, 98.09it/s]

⚠️ Skipping 5QDH_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7NGC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7PB0_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  26%|█▊     | 1655/6340 [00:17<00:45, 102.10it/s]

⚠️ Skipping 4AUA_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6MD2_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  27%|█▊     | 1685/6340 [00:18<00:38, 120.66it/s]

⚠️ Skipping 3WIZ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6X48_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3ADX_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2ZK6_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7A04_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  27%|██▏     | 1711/6340 [00:18<00:58, 79.18it/s]

⚠️ Skipping 6KB2_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9HJC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9BVQ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5OSY_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  28%|█▉     | 1756/6340 [00:18<00:43, 104.76it/s]

⚠️ Skipping 6WCV_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6UVE_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8OUT_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2C90_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  28%|█▉     | 1780/6340 [00:18<00:42, 108.29it/s]

⚠️ Skipping 7VUU_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4OIL_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  28%|█▉     | 1806/6340 [00:19<00:39, 115.04it/s]

⚠️ Skipping 5OOG_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8FE7_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  29%|██     | 1855/6340 [00:19<00:39, 112.81it/s]

⚠️ Skipping 2XBA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  30%|██     | 1894/6340 [00:19<00:36, 120.62it/s]

⚠️ Skipping 6KB7_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6KYP_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5Y1Y_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  30%|██     | 1921/6340 [00:20<00:37, 117.85it/s]

⚠️ Skipping 5A54_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5DV8_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6MA4_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4H4B_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  31%|██▏    | 1973/6340 [00:20<00:42, 101.93it/s]

⚠️ Skipping 9BVO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  32%|██▌     | 2010/6340 [00:21<00:45, 95.19it/s]

⚠️ Skipping 2C93_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6CDR_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  32%|██▎    | 2045/6340 [00:21<00:41, 103.55it/s]

⚠️ Skipping 2AX6_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  33%|██▎    | 2097/6340 [00:21<00:35, 119.02it/s]

⚠️ Skipping 5YXB_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6P0P_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8A2J_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5DVC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7LH8_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  34%|██▋     | 2134/6340 [00:22<00:42, 98.50it/s]

⚠️ Skipping 8OQY_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7E0A_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  34%|██▋     | 2167/6340 [00:22<00:41, 99.94it/s][17:09:25] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:25] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry

⚠️ Skipping 6CD6_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  35%|██▊     | 2201/6340 [00:23<00:41, 99.48it/s]

⚠️ Skipping 2X81_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  36%|██▉     | 2312/6340 [00:24<00:40, 98.98it/s]

⚠️ Skipping 2YGO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  37%|██▉     | 2351/6340 [00:24<00:40, 98.20it/s]

⚠️ Skipping 3QVU_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1F42_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7OPS_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5G3J_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  37%|██▉     | 2376/6340 [00:24<00:42, 94.16it/s]

⚠️ Skipping 5EY4_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  39%|███     | 2454/6340 [00:25<00:41, 93.75it/s]

⚠️ Skipping 7U8G_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8WGC_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  39%|██▊    | 2492/6340 [00:26<00:35, 108.35it/s]

⚠️ Skipping 2ZK5_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  40%|███▏    | 2543/6340 [00:26<00:38, 99.45it/s]

⚠️ Skipping 8OGI_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  40%|██▊    | 2567/6340 [00:26<00:37, 101.59it/s]

⚠️ Skipping 2O2M_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4CGA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  41%|██▉    | 2619/6340 [00:27<00:31, 118.42it/s]

⚠️ Skipping 5D65_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  42%|██▉    | 2658/6340 [00:27<00:30, 122.27it/s]

⚠️ Skipping 6ONI_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8CSQ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  42%|██▉    | 2685/6340 [00:27<00:29, 124.40it/s]

⚠️ Skipping 5DWL_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6X3L_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  43%|███    | 2737/6340 [00:28<00:30, 118.56it/s]

⚠️ Skipping 1QBV_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  44%|███    | 2762/6340 [00:28<00:30, 117.08it/s]

⚠️ Skipping 5DV6_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3CWD_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  44%|███    | 2803/6340 [00:28<00:27, 129.03it/s]

⚠️ Skipping 5XTC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5UUT_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6BYZ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2YGP_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  45%|███▏   | 2842/6340 [00:29<00:29, 118.39it/s]

⚠️ Skipping 8DKN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7B9X_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  45%|███▏   | 2868/6340 [00:29<00:30, 113.38it/s]

⚠️ Skipping 9GU2_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7RK3_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8VPN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8HUM_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7Y5Z_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  46%|███▏   | 2898/6340 [00:29<00:29, 115.36it/s]

⚠️ Skipping 7YNM_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  46%|███▏   | 2940/6340 [00:29<00:27, 122.39it/s]

⚠️ Skipping 7PSZ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  48%|███▎   | 3017/6340 [00:30<00:30, 108.73it/s]

⚠️ Skipping 8ZFN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6S9Q_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3MXF_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  48%|███▎   | 3043/6340 [00:30<00:30, 107.12it/s]

⚠️ Skipping 4UDC_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  49%|███▍   | 3094/6340 [00:31<00:27, 119.82it/s]

⚠️ Skipping 5YXJ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3B68_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  49%|███▍   | 3137/6340 [00:31<00:24, 130.61it/s]

⚠️ Skipping 8A2K_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8KCU_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4BR3_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  50%|███▌   | 3177/6340 [00:32<00:25, 121.94it/s]

⚠️ Skipping 6AVI_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3ZM9_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6M90_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  51%|████    | 3232/6340 [00:32<00:32, 95.93it/s]

⚠️ Skipping 6TD8_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7BPZ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  52%|███▌   | 3266/6340 [00:32<00:29, 102.98it/s]

⚠️ Skipping 4TPW_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7NDO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  52%|████▏   | 3287/6340 [00:33<00:36, 84.62it/s]

⚠️ Skipping 3SW7_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  53%|███▋   | 3368/6340 [00:33<00:26, 110.24it/s]

⚠️ Skipping 8FHE_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  54%|███▊   | 3428/6340 [00:34<00:26, 108.80it/s]

⚠️ Skipping 6AGF_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7A06_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1ST4_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  55%|███▊   | 3467/6340 [00:34<00:24, 116.45it/s]

⚠️ Skipping 5QE0_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6L36_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9JQQ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  55%|███▊   | 3509/6340 [00:35<00:22, 128.13it/s]

⚠️ Skipping 2C5Y_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4CG8_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7WGL_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  56%|███▉   | 3547/6340 [00:35<00:23, 116.45it/s]

⚠️ Skipping 6O5I_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5QIO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  57%|███▉   | 3599/6340 [00:35<00:23, 114.38it/s]

⚠️ Skipping 5WR1_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5YVC_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  57%|████   | 3627/6340 [00:36<00:25, 105.12it/s]

⚠️ Skipping 7BJL_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  58%|████   | 3666/6340 [00:36<00:22, 116.91it/s]

⚠️ Skipping 7BYM_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 18GS_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  58%|████   | 3707/6340 [00:36<00:22, 115.57it/s]

⚠️ Skipping 2AXA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  59%|████   | 3731/6340 [00:37<00:23, 112.34it/s]

⚠️ Skipping 6CM1_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  59%|████▏  | 3768/6340 [00:37<00:22, 113.44it/s]

⚠️ Skipping 6T1S_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7V10_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4R2U_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  61%|████▏  | 3843/6340 [00:38<00:21, 115.16it/s]

⚠️ Skipping 3R8V_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  63%|█████   | 3964/6340 [00:39<00:25, 93.84it/s][17:09:42] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:42] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  63%|█████   | 3974/6340 [00:39<00:25, 94.18it/s]

⚠️ Skipping 5DV3_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  63%|████▍  | 4011/6340 [00:39<00:21, 108.74it/s]

⚠️ Skipping 3SP7_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8QZ6_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  64%|████▌  | 4088/6340 [00:40<00:18, 120.42it/s]

⚠️ Skipping 8SSB_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6T2H_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  65%|████▌  | 4128/6340 [00:40<00:18, 122.34it/s]

⚠️ Skipping 2AX8_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7SHO_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1YSN_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  66%|████▌  | 4177/6340 [00:41<00:20, 104.79it/s]

⚠️ Skipping 7O6J_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  66%|████▋  | 4199/6340 [00:41<00:20, 102.94it/s][17:09:44] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:44] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  67%|████▋  | 4221/6340 [00:41<00:20, 104.39it/s]

⚠️ Skipping 3U0Y_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7VNP_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  67%|█████▍  | 4276/6340 [00:42<00:22, 93.46it/s]

⚠️ Skipping 6Q8P_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9EIJ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  68%|█████▍  | 4308/6340 [00:42<00:21, 95.64it/s]

⚠️ Skipping 6L37_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  69%|█████▌  | 4372/6340 [00:43<00:20, 96.89it/s]

⚠️ Skipping 3QKD_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  70%|████▉  | 4418/6340 [00:43<00:17, 108.35it/s]

⚠️ Skipping 6X21_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6W9E_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  71%|████▉  | 4490/6340 [00:44<00:16, 113.09it/s]

⚠️ Skipping 7BYL_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7BJ0_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  71%|████▉  | 4515/6340 [00:44<00:15, 117.68it/s]

⚠️ Skipping 6N54_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  72%|█████  | 4553/6340 [00:45<00:17, 101.43it/s]

⚠️ Skipping 3H0B_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  73%|█████▏ | 4651/6340 [00:45<00:14, 114.29it/s]

⚠️ Skipping 7ZEJ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  74%|█████▏ | 4712/6340 [00:46<00:14, 115.21it/s]

⚠️ Skipping 2WD1_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  75%|█████▉  | 4735/6340 [00:46<00:16, 98.56it/s]

⚠️ Skipping 8H4R_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  75%|█████▎ | 4757/6340 [00:46<00:15, 102.17it/s][17:09:49] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:49] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  75%|█████▎ | 4769/6340 [00:47<00:14, 106.48it/s]

⚠️ Skipping 7VUS_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2HIW_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2CKQ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  76%|█████▎ | 4819/6340 [00:47<00:13, 114.78it/s]

⚠️ Skipping 8SZI_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6GNK_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  77%|█████▎ | 4855/6340 [00:47<00:13, 109.51it/s]

⚠️ Skipping 2F9B_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7Y5X_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  77%|█████▍ | 4880/6340 [00:48<00:12, 114.62it/s]

⚠️ Skipping 9DMJ_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  78%|█████▍ | 4915/6340 [00:48<00:13, 106.84it/s]

⚠️ Skipping 7PAX_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  79%|██████▎ | 4987/6340 [00:49<00:14, 93.36it/s]

⚠️ Skipping 2W1I_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8P2R_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9GU3_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  80%|██████▍ | 5062/6340 [00:49<00:13, 97.14it/s]

⚠️ Skipping 2O2N_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4OIU_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5T1T_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  80%|██████▍ | 5085/6340 [00:50<00:12, 98.48it/s]

⚠️ Skipping 4OGH_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5YV8_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  81%|██████▍ | 5118/6340 [00:50<00:13, 87.83it/s]

⚠️ Skipping 4OHA_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  81%|██████▍ | 5137/6340 [00:50<00:15, 75.46it/s]

⚠️ Skipping 6VEI_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  82%|█████▋ | 5194/6340 [00:51<00:11, 103.37it/s]

⚠️ Skipping 6E4L_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8SZG_protein_ligand_rdkit.sdf (cannot read molecule)

[17:09:54] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:54] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  82%|█████▊ | 5228/6340 [00:51<00:10, 104.41it/s]

⚠️ Skipping 7V12_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  83%|█████▊ | 5270/6340 [00:52<00:08, 126.55it/s]

⚠️ Skipping 6W4F_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3B66_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8OZ2_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  85%|█████▉ | 5359/6340 [00:52<00:08, 119.01it/s]

⚠️ Skipping 7V11_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  85%|█████▉ | 5410/6340 [00:53<00:07, 121.57it/s]

⚠️ Skipping 9EII_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7FQX_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7CVN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5V57_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  86%|██████ | 5472/6340 [00:53<00:08, 107.79it/s]

⚠️ Skipping 5YXL_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  87%|██████ | 5513/6340 [00:54<00:06, 121.80it/s]

⚠️ Skipping 9EOT_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 6U2G_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  88%|██████▏| 5552/6340 [00:54<00:06, 118.87it/s]

⚠️ Skipping 1A3E_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8P78_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  88%|██████▏| 5588/6340 [00:54<00:06, 114.95it/s]

⚠️ Skipping 3B0R_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2AX9_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  89%|██████▏| 5613/6340 [00:55<00:06, 115.53it/s]

⚠️ Skipping 7EZR_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 5QFX_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  89%|███████ | 5636/6340 [00:55<00:07, 91.99it/s]

⚠️ Skipping 1MUE_protein_ligand_rdkit.sdf (cannot read molecule)

[17:09:58] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:09:58] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  89%|██████▎| 5661/6340 [00:55<00:06, 101.49it/s]

⚠️ Skipping 6PTW_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  91%|███████▎| 5753/6340 [00:56<00:06, 93.32it/s]

⚠️ Skipping 8OUO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  91%|███████▎| 5791/6340 [00:57<00:06, 82.77it/s]

⚠️ Skipping 7UEO_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  92%|███████▎| 5822/6340 [00:57<00:05, 90.68it/s]

⚠️ Skipping 4YUR_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  93%|███████▍| 5875/6340 [00:58<00:04, 99.22it/s]

⚠️ Skipping 6CDF_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 1HPK_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  94%|███████▍| 5935/6340 [00:58<00:04, 92.25it/s]

⚠️ Skipping 5U77_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3INQ_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7A1L_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  94%|███████▌| 5975/6340 [00:59<00:04, 82.72it/s]

⚠️ Skipping 2YGN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7NEU_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  95%|███████▌| 6008/6340 [00:59<00:03, 95.72it/s]

⚠️ Skipping 6T3P_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 9EIH_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4Y29_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  96%|███████▋| 6117/6340 [01:00<00:02, 99.47it/s]

⚠️ Skipping 7NV0_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  97%|██████▊| 6178/6340 [01:01<00:01, 109.16it/s]

⚠️ Skipping 7QY1_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  98%|██████▊| 6206/6340 [01:01<00:01, 120.33it/s]

⚠️ Skipping 7C6Q_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 7YNN_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 3F1O_protein_ligand_rdkit.sdf (cannot read molecule)

[17:10:04] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
[17:10:04] WARNING: not removing hydrogen atom with neighbor that has non-tetrahedral stereochemistry
Calculating RDKit descriptors:  98%|██████▉| 6243/6340 [01:01<00:00, 114.40it/s]

⚠️ Skipping 7BQ0_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 8ROK_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors:  99%|██████▉| 6297/6340 [01:02<00:00, 120.82it/s]

⚠️ Skipping 6UVC_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2SHP_protein_ligand_rdkit.sdf (cannot read molecule)

Calculating RDKit descriptors: 100%|███████| 6340/6340 [01:02<00:00, 101.11it/s]

⚠️ Skipping 4UDD_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 2R3Q_protein_ligand_rdkit.sdf (cannot read molecule)
⚠️ Skipping 4R6S_protein_ligand_rdkit.sdf (cannot read molecule)

✅ RDKit descriptors saved successfully at:
/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_test.csv

In [9]:
import pandas as pd
df_rdkit_test = pd.read_csv("/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_test.csv")
df_rdkit_test.head()

,Complex_ID,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,4CWF_protein_ligand_rdkit,5.675801,5.675801,0.292135,0.292135,0.724529,11.352941,227.271,214.167,227.117095,...,0,0,0,0,0,0,0,0,0,0
1,6ZRC_protein_ligand_rdkit,15.210403,15.210403,0.009959,-1.702824,0.017090,24.666667,1769.205,1637.157,1767.959951,...,2,0,0,0,0,0,0,0,2,0
2,1L5Q_protein_ligand_rdkit,10.731864,10.731864,0.445065,-1.465046,0.337239,41.266667,221.209,206.089,221.089937,...,0,0,0,0,0,0,0,0,0,0
3,5RK9_protein_ligand_rdkit,11.071481,11.071481,0.033565,-0.033565,0.600005,9.400000,139.158,130.086,139.074562,...,0,0,0,0,0,0,0,0,0,0
4,8CPH_protein_ligand_rdkit,10.590634,10.590634,0.107882,-0.923506,0.496581,10.428571,323.805,309.693,323.049525,...,1,0,0,0,0,0,0,0,0,0

In [11]:
print(list(df_rdkit_test.columns))

['Complex_ID', 'MaxAbsEStateIndex', 'MaxEStateIndex', 'MinAbsEStateIndex', 'MinEStateIndex', 'qed', 'SPS', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons', 'NumRadicalElectrons', 'MaxPartialCharge', 'MinPartialCharge', 'MaxAbsPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2', 'FpDensityMorgan3', 'BCUT2D_MWHI', 'BCUT2D_MWLOW', 'BCUT2D_CHGHI', 'BCUT2D_CHGLO', 'BCUT2D_LOGPHI', 'BCUT2D_LOGPLOW', 'BCUT2D_MRHI', 'BCUT2D_MRLOW', 'AvgIpc', 'BalabanJ', 'BertzCT', 'Chi0', 'Chi0n', 'Chi0v', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n', 'Chi2v', 'Chi3n', 'Chi3v', 'Chi4n', 'Chi4v', 'HallKierAlpha', 'Ipc', 'Kappa1', 'Kappa2', 'Kappa3', 'LabuteASA', 'PEOE_VSA1', 'PEOE_VSA10', 'PEOE_VSA11', 'PEOE_VSA12', 'PEOE_VSA13', 'PEOE_VSA14', 'PEOE_VSA2', 'PEOE_VSA3', 'PEOE_VSA4', 'PEOE_VSA5', 'PEOE_VSA6', 'PEOE_VSA7', 'PEOE_VSA8', 'PEOE_VSA9', 'SMR_VSA1', 'SMR_VSA10', 'SMR_VSA2', 'SMR_VSA3', 'SMR_VSA4', 'SMR_VSA5', 'SMR_VSA6', 'SMR_VSA7', 'SMR_VSA8', 'SMR_VSA9', 'SlogP_VSA1', 'SlogP_VSA10', 'SlogP_VSA11', 'SlogP_VSA12', 'SlogP_VSA2', 'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA7', 'SlogP_VSA8', 'SlogP_VSA9', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'EState_VSA11', 'EState_VSA2', 'EState_VSA3', 'EState_VSA4', 'EState_VSA5', 'EState_VSA6', 'EState_VSA7', 'EState_VSA8', 'EState_VSA9', 'VSA_EState1', 'VSA_EState10', 'VSA_EState2', 'VSA_EState3', 'VSA_EState4', 'VSA_EState5', 'VSA_EState6', 'VSA_EState7', 'VSA_EState8', 'VSA_EState9', 'FractionCSP3', 'HeavyAtomCount', 'NHOHCount', 'NOCount', 'NumAliphaticCarbocycles', 'NumAliphaticHeterocycles', 'NumAliphaticRings', 'NumAmideBonds', 'NumAromaticCarbocycles', 'NumAromaticHeterocycles', 'NumAromaticRings', 'NumAtomStereoCenters', 'NumBridgeheadAtoms', 'NumHAcceptors', 'NumHDonors', 'NumHeteroatoms', 'NumHeterocycles', 'NumRotatableBonds', 'NumSaturatedCarbocycles', 'NumSaturatedHeterocycles', 'NumSaturatedRings', 'NumSpiroAtoms', 'NumUnspecifiedAtomStereoCenters', 'Phi', 'RingCount', 'MolLogP', 'MolMR', 'fr_Al_COO', 'fr_Al_OH', 'fr_Al_OH_noTert', 'fr_ArN', 'fr_Ar_COO', 'fr_Ar_N', 'fr_Ar_NH', 'fr_Ar_OH', 'fr_COO', 'fr_COO2', 'fr_C_O', 'fr_C_O_noCOO', 'fr_C_S', 'fr_HOCCN', 'fr_Imine', 'fr_NH0', 'fr_NH1', 'fr_NH2', 'fr_N_O', 'fr_Ndealkylation1', 'fr_Ndealkylation2', 'fr_Nhpyrrole', 'fr_SH', 'fr_aldehyde', 'fr_alkyl_carbamate', 'fr_alkyl_halide', 'fr_allylic_oxid', 'fr_amide', 'fr_amidine', 'fr_aniline', 'fr_aryl_methyl', 'fr_azide', 'fr_azo', 'fr_barbitur', 'fr_benzene', 'fr_benzodiazepine', 'fr_bicyclic', 'fr_diazo', 'fr_dihydropyridine', 'fr_epoxide', 'fr_ester', 'fr_ether', 'fr_furan', 'fr_guanido', 'fr_halogen', 'fr_hdrzine', 'fr_hdrzone', 'fr_imidazole', 'fr_imide', 'fr_isocyan', 'fr_isothiocyan', 'fr_ketone', 'fr_ketone_Topliss', 'fr_lactam', 'fr_lactone', 'fr_methoxy', 'fr_morpholine', 'fr_nitrile', 'fr_nitro', 'fr_nitro_arom', 'fr_nitro_arom_nonortho', 'fr_nitroso', 'fr_oxazole', 'fr_oxime', 'fr_para_hydroxylation', 'fr_phenol', 'fr_phenol_noOrthoHbond', 'fr_phos_acid', 'fr_phos_ester', 'fr_piperdine', 'fr_piperzine', 'fr_priamide', 'fr_prisulfonamd', 'fr_pyridine', 'fr_quatN', 'fr_sulfide', 'fr_sulfonamd', 'fr_sulfone', 'fr_term_acetylene', 'fr_tetrazole', 'fr_thiazole', 'fr_thiocyan', 'fr_thiophene', 'fr_unbrch_alkane', 'fr_urea']

Finding out overlapping complexes between training and external datasets

In [19]:
import pandas as pd

# File paths
train_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_train.csv"
test_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_test.csv"

# Load both datasets
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Extract Complex_ID columns
train_ids = set(train_df["Complex_ID"].astype(str).str.lower())
test_ids = set(test_df["Complex_ID"].astype(str).str.lower())

# Find common IDs
common_ids = train_ids.intersection(test_ids)

# Print results
print(f"✅ Number of common Complex_IDs: {len(common_ids)}")
if common_ids:
    print("Common IDs:")
    print(common_ids)
else:
    print("🎉 No common Complex_IDs found between train and test!")

✅ Number of common Complex_IDs: 770
Common IDs:
{'4lm5', '3vby', '2xf0', '5c26', '3fyj', '4jlm', '2wmw', '5d7a', '4kcg', '4cmu', '4ot6', '4bcf', '2i6a', '3fv8', '3vbt', '2vto', '3byu', '5idp', '4y73', '4zts', '4q9s', '4y46', '4hvb', '2wu6', '4jx7', '4yne', '3e7o', '6ayd', '3kc3', '4d2t', '5t18', '5jrs', '4qmm', '4hnf', '4fny', '4qmv', '2p3g', '6fil', '5kbq', '5t1s', '4otg', '6e2n', '5vcx', '3kvw', '2ym7', '4l02', '1gi9', '5bnj', '3tku', '5kpm', '4joa', '3zim', '6fyp', '5opu', '1pye', '4bkj', '4alv', '4c4e', '4oth', '4ppb', '3cy2', '4bci', '5jq8', '3qd3', '3r01', '1h1p', '4wsy', '5ftq', '3gp0', '6dkg', '4y5h', '6ft8', '6mx8', '1pxk', '5v24', '3rtp', '5csw', '5gjd', '4v04', '4hys', '5a4q', '3vbq', '1o4n', '4at3', '4mq2', '2wih', '5l6o', '2w1h', '4cfe', '3dpd', '3v3v', '4rpv', '4mp2', '1uwh', '3nw6', '3prz', '4hcu', '5lxc', '3tti', '4aw5', '4i0t', '3zw3', '6db3', '4y83', '5jga', '4q1b', '3fi2', '5hfu', '4hgl', '4zjj', '5tc0', '4yti', '1unl', '4erw', '3e3b', '3p9j', '3g90', '6nfz', '4d2s', '5ubt', '5w4w', '3fy0', '4ppc', '5n87', '3jpv', '1sm2', '6b5j', '4kio', '5hg1', '4nus', '3ds6', '5auv', '4ezj', '4jg7', '5icp', '1aq1', '6m8d', '5ap7', '3kck', '4ztl', '3tcp', '5ap4', '1o45', '5u6c', '4waf', '4kbk', '4x21', '2waj', '1w84', '5n7v', '4c4j', '1o4h', '5av0', '4dli', '2i0e', '1o4d', '2xbj', '5xyz', '3f88', '4ppa', '2b1p', '2zdx', '3f82', '6s9c', '4qmq', '5twz', '3srv', '3nyn', '1t5a', '2xke', '4bid', '5m4k', '4qmw', '4fob', '5iuh', '4z9l', '4anq', '6qg4', '3anq', '2pzy', '3r02', '2zdt', '2g9x', '3pxz', '3hvc', '4fjz', '2io6', '5xvf', '2og8', '5x02', '4c4h', '5ei6', '2fb8', '4yff', '3fyk', '2vww', '3zbf', '3jxw', '5opv', '2x9f', '6qho', '3fzs', '1pf8', '4byi', '2xp2', '4aa0', '1zrz', '5a9u', '5ihc', '5jgb', '2obj', '3d9v', '4ezk', '4umu', '4d2v', '5iha', '4mq1', '3zls', '4hyu', '2yer', '5ei2', '3vry', '5n9k', '4xh6', '4ps8', '3nw5', '2r4b', '2wti', '4d2p', '4urk', '4cnh', '3ppj', '4uwf', '1r78', '2etr', '3bys', '5ap6', '6m8e', '4g9c', '4h1j', '4xs2', '1u59', '3nzu', '4kz0', '2xey', '3f2a', '5eak', '6cz4', '3apc', '3u8w', '4g11', '3f5p', '4zy5', '1o43', '5hex', '3zvv', '2c6e', '6m88', '4fod', '4olh', '6di0', '3v5j', '4xv9', '3o2m', '4mf1', '5y5u', '5m51', '2xiy', '3mj1', '6m8c', '5vdk', '3tv7', '4mpc', '3da6', '3gc7', '3v6r', '3ptg', '5ei8', '4qmt', '5d9l', '6n9p', '1oiu', '4pqn', '5tx3', '4nct', '3ipy', '5a3x', '2vth', '5vo2', '5wfj', '3lxl', '5x5o', '6aah', '4bic', '5kcx', '1pmv', '3q4c', '6m9l', '1pxm', '3l16', '1m51', '6ej4', '6e2o', '3que', '4w4w', '4ps7', '5n9s', '4l53', '3efw', '3oxi', '3v6s', '2izx', '5j71', '4bie', '6few', '5vee', '4jlj', '4c4f', '4d2w', '5t23', '4n6y', '3mvl', '5opr', '3g0f', '6i3u', '5tur', '4j6i', '1o4j', '4bhn', '4af3', '5z1e', '3uyt', '3lvp', '4txc', '4zlo', '5aaa', '5vil', '3lq5', '6m8a', '4bdc', '6pl2', '3r04', '4i4e', '6f7b', '4mp7', '5idn', '3r9d', '4g17', '3c1x', '2oic', '4pp7', '5loh', '1yhs', '3u4u', '4tv3', '3qd4', '4ckr', '5tkd', '6aud', '4hgt', '1o4f', '4aa4', '6qft', '5e8w', '4d0x', '3vbx', '2hy0', '4ehv', '4u79', '4kb8', '4aof', '2ok1', '2bdj', '3m11', '4anx', '6emh', '2zv2', '3coh', '4d1s', '4g16', '3gcv', '4w9w', '5up3', '3r0t', '5a4l', '3new', '2b7a', '2o3p', '2esm', '3v8w', '3jy9', '2bu5', '3v8t', '3s4q', '5aab', '4qo9', '1pmn', '3umx', '4afe', '6fyk', '5uiq', '3rni', '4ewh', '6gl3', '5k5n', '5csh', '5k00', '3v5l', '5y86', '5h2u', '5aac', '4umr', '5na0', '5eko', '1o4o', '2p33', '4hvi', '3hdn', '2in6', '1tvo', '5u6b', '3tl5', '4kbc', '1pxj', '5d9k', '3wyy', '3mj2', '4mxc', '3u9n', '2dq7', '5wg4', '4q1c', '3aox', '4y85', '3fzr', '1o47', '4xhk', '5j8i', '6edl', '4ph4', '3m2w', '4cfm', '5es1', '5tex', '4bib', '2w1d', '4ckj', '5ntt', '3kvx', '3vqh', '3zlw', '3vw6', '4c4i', '4bky', '5a4e', '5nad', '2yak', '3nlb', '5m56', '5ap2', '4q1a', '3g9l', '3pp0', '3r7q', '5amn', '5iug', '3gb2', '4azf', '4bkz', '6gzh', '3nzs', '5auw', '2exc', '5td2', '4h1m', '5bms', '5kqd', '5oq4', '4whz', '2xix', '4itj', '5hvu', '4v25', '4nw5', '3qts', '2jbp', '4aqc', '5ap3', '6m89', '2a5u', '3vnt', '6ar4', '4umt', '1wcc', '4pp9', '4dbn', '4ty1', '5kx8', '4cli', '5ekn', '3vbw', '4kip', '6fyi', '2e2b', '4bi1', '4q9z', '3nw7', '6e0r', '5aa8', '6h3k', '3pix', '1o4i', '4w4y', '3rzb', '4qmu', '4d0w', '3fpm', '5bvf', '5uox', '4ksp', '4z3v', '2o65', '1yi3', '4o0v', '4izy', '1h01', '1v1k', '6fyl', '6qat', '3ppk', '5v5y', '4kba', '5iu2', '4bdk', '2ydj', '5m53', '6op9', '4fnz', '2iw6', '2o64', '1urw', '2q8i', '2j4z', '2vwv', '3w55', '3mb6', '5okt', '5dh3', '5hes', '4hct', '4hyh', '3gfw', '5aux', '3hdm', '3nnv', '4dfn', '4dce', '3uok', '4zsa', '3fhr', '3fdn', '4py1', '6nfi', '6mt0', '4yp8', '5jzn', '5lma', '6b4w', '2z7r', '4xg8', '4agd', '4r3c', '3g9n', '1o5b', '3fqs', '5kzi', '4ps3', '3r7r', '4qms', '3rk9', '5uor', '4gv1', '5ih8', '4uxl', '6h0u', '2jdv', '4hvg', '3r00', '4mpe', '5xg4', '5unp', '5auu', '4ez5', '5vt1', '4qmx', '3hv6', '5jha', '5auz', '3dcv', '5kkr', '3anr', '5em5', '4jg8', '4w4x', '4cmt', '4q18', '4pte', '3fxw', '4ez3', '3ma3', '3a2c', '5j87', '1xo2', '4jg6', '3zos', '5vio', '3ot3', '5z1d', '6sfj', '4alu', '5oq7', '4q1d', '3rk5', '3fup', '6cqf', '3iw7', '6fex', '4n70', '2xno', '6c1s', '5m4f', '4njd', '4qmz', '4bcg', '4bcj', '5vc6', '5vo6', '4xg4', '5tt7', '5o11', '6hm7', '4oti', '6c0u', '4lmu', '3pxy', '6n7c', '6ft9', '4eyj', '3oy1', '2wmx', '5i0b', '6oyw', '5j1v', '5hzn', '5x8i', '3l17', '4c4g', '5htc', '4yfi', '5lxd', '4ztn', '3lfs', '3sd5', '4cff', '3l13', '4eon', '5ztn', '2vwu', '3rak', '3ig7', '6fer', '6m8b', '4eym', '3vbv', '4cfu', '6qhr', '4i6f', '5iui', '3txo', '4hgs', '6e2m', '5twl', '3r2b', '3w1f', '3vs3', '6eil', '6gmd', '4hcv', '6fyv', '4rfz', '4tpt', '5l6p', '2xkf', '5hvy', '4umq', '3vc4', '5m4u', '4idt', '6ohd', '2iw8', '2o63', '5ap0', '3c4e', '4qna', '5ap5', '5auy', '4x7q', '3l54', '2a4z', '4aze', '4q1e', '3c5u', '5bue', '4ezl', '4foc', '6nzh', '3wzu', '2bmc', '5o91', '5h0b', '4mf0', '2x9e', '4nw6', '3oaw', '4mbj', '5v5n', '4qmn', '5ceo', '3s1h', '2wu7', '5toe', '3rah', '4m0z', '3uzp', '5ax9', '5a4t', '5v19', '4oys', '5fdp', '3ps6', '5eol', '2hxq', '5mqv', '3bbt', '4yo6', '3gcq', '4ztm', '5w86', '4alw', '3hhm', '1h0w', '5uis', '6eip', '5kkt', '6ng0', '3o96', '1xbc', '6ebw', '2o2u', '3ttj', '4rg0', '3uix', '5j5t', '3ns9', '3kb7', '6qg7', '4w4v', '3wi6', '4idv', '6ekd'}

Removing overlapping complexes from external dataset ECIF descriptors

In [22]:
import pandas as pd

# File paths
train_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_train.csv"
test_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_test.csv"
output_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_test_clean.csv"

# Load data
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Convert Complex_ID to lowercase for matching
train_ids = set(train_df["Complex_ID"].astype(str).str.lower())
test_df["Complex_ID_lower"] = test_df["Complex_ID"].astype(str).str.lower()

# Filter out overlapping Complex_IDs
test_df_clean = test_df[~test_df["Complex_ID_lower"].isin(train_ids)].copy()

# Drop helper column
test_df_clean.drop(columns=["Complex_ID_lower"], inplace=True)

# Save the cleaned test file
test_df_clean.to_csv(output_path, index=False)

print(f" Cleaned test file saved at: {output_path}")
print(f" Removed {len(test_df) - len(test_df_clean)} overlapping Complex_IDs")
print(f"Final test set size: {len(test_df_clean)}")

✅ Cleaned test file saved at: /media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_test_clean.csv
🧹 Removed 770 overlapping Complex_IDs
✅ Final test set size: 5265

Merging ECIF and RDKit descriptors of training dataset

In [1]:
import pandas as pd

# File paths
ecif_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_with_activity_train.csv"
rdkit_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_train.csv"

# Load both dataframes
df_ecif = pd.read_csv(ecif_path)
df_rdkit = pd.read_csv(rdkit_path)

# Clean the RDKit Complex_ID column by removing '_ligand_rdkit'
df_rdkit["Complex_ID"] = df_rdkit["Complex_ID"].str.replace("_ligand_rdkit", "", regex=False)

# Merge based on Complex_ID
merged_df = pd.merge(df_ecif, df_rdkit, on="Complex_ID", how="inner")

# Save merged dataframe
merged_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_train_full.csv"
merged_df.to_csv(merged_path, index=False)

print(f"✅ Merged file saved successfully: {merged_path}")
print("Merged dataframe shape:", merged_df.shape)
print("Example rows:")
print(merged_df.head())

✅ Merged file saved successfully: /media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_train_full.csv
Merged dataframe shape: (2337, 1759)
Example rows:
  Complex_ID  C;4;1;3;0;0-Br;1;1;0;0;0  C;4;1;3;0;0-C;3;3;0;1;1  \
0       3r02                         8                        0
1       6c2t                         0                        0
2       5t31                         0                        0
3       4eop                         0                        0
4       2ghg                         0                        0

   C;4;1;3;0;0-C;4;1;1;0;0  C;4;1;3;0;0-C;4;1;2;0;0  C;4;1;3;0;0-C;4;1;3;0;0  \
0                        0                        0                        0
1                        0                        0                        0
2                        0                        0                        8
3                        0                        0                        0
4                        0                        0                        0

   C;4;1;3;0;0-C;4;2;0;0;0  C;4;1;3;0;0-C;4;2;1;0;0  C;4;1;3;0;0-C;4;2;1;0;1  \
0                        0                        0                       27
1                        0                        0                       47
2                        0                        0                       20
3                        0                        8                       49
4                        0                        6                       38

   C;4;1;3;0;0-C;4;2;1;1;1  ...  fr_sulfide  fr_sulfonamd  fr_sulfone  \
0                        0  ...           0             0           0
1                        0  ...           0             0           0
2                        0  ...           0             0           0
3                        0  ...           1             0           0
4                        0  ...           0             0           0

   fr_term_acetylene  fr_tetrazole  fr_thiazole  fr_thiocyan  fr_thiophene  \
0                  0             0            0            0             0
1                  0             0            1            0             0
2                  0             0            0            0             0
3                  0             0            0            0             1
4                  0             0            0            0             0

   fr_unbrch_alkane  fr_urea
0                 0        0
1                 0        0
2                 0        0
3                 0        0
4                 0        0

[5 rows x 1759 columns]

Merging ECIF and RDKit descriptors of external dataset

In [27]:
import pandas as pd

# File paths
ecif_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Trial/ECIF_descriptors_test.csv"
rdkit_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/rdkit_descriptors_test.csv"

# Load both dataframes
df_ecif = pd.read_csv(ecif_path)
df_rdkit = pd.read_csv(rdkit_path)

# Clean the RDKit Complex_ID column by removing '_ligand_rdkit'
df_rdkit["Complex_ID"] = df_rdkit["Complex_ID"].str.replace("_protein_ligand_rdkit", "", regex=False)

# Merge based on Complex_ID
merged_df = pd.merge(df_ecif, df_rdkit, on="Complex_ID", how="inner")

# Save merged dataframe
merged_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test.csv"
merged_df.to_csv(merged_path, index=False)

print(f"✅ Merged file saved successfully: {merged_path}")
print("Merged dataframe shape:", merged_df.shape)
print("Example rows:")
print(merged_df.head())

✅ Merged file saved successfully: /media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test.csv
Merged dataframe shape: (6035, 1758)
Example rows:
  Complex_ID  C;4;1;3;0;0-Br;1;1;0;0;0  C;4;1;3;0;0-C;3;3;0;1;1  \
0       4CWF                         0                        0
1       6ZRC                         0                        0
2       1L5Q                         0                        0
3       5RK9                         0                        0
4       8CPH                         0                        0

   C;4;1;3;0;0-C;4;1;1;0;0  C;4;1;3;0;0-C;4;1;2;0;0  C;4;1;3;0;0-C;4;1;3;0;0  \
0                        0                        0                        3
1                        0                        0                        9
2                        0                        0                        3
3                        0                        0                        8
4                        0                        0                        6

   C;4;1;3;0;0-C;4;2;0;0;0  C;4;1;3;0;0-C;4;2;1;0;0  C;4;1;3;0;0-C;4;2;1;0;1  \
0                        0                        0                       15
1                        0                        0                        2
2                        0                        0                        0
3                        0                        0                        5
4                        0                        0                       28

   C;4;1;3;0;0-C;4;2;1;1;1  ...  fr_sulfide  fr_sulfonamd  fr_sulfone  \
0                        0  ...           0             0           0
1                        0  ...           2             0           0
2                        0  ...           0             0           0
3                        0  ...           0             0           0
4                        0  ...           1             0           0

   fr_term_acetylene  fr_tetrazole  fr_thiazole  fr_thiocyan  fr_thiophene  \
0                  0             0            0            0             0
1                  0             0            0            0             0
2                  0             0            0            0             0
3                  0             0            0            0             0
4                  0             0            0            0             0

   fr_unbrch_alkane  fr_urea
0                 0        0
1                 2        0
2                 0        0
3                 0        0
4                 0        0

[5 rows x 1758 columns]

Removing overlapping complexes from external dataset ECIF and RDKit merged descriptors

In [3]:
import pandas as pd

# File paths
train_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/merged_clean.csv"
test_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test.csv"
output_path = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test_nonoverlapped.csv"

# Load data
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Convert Complex_ID to lowercase for matching
train_ids = set(train_df["Complex_ID"].astype(str).str.lower())
test_df["Complex_ID_lower"] = test_df["Complex_ID"].astype(str).str.lower()

# Filter out overlapping Complex_IDs
test_df_clean = test_df[~test_df["Complex_ID_lower"].isin(train_ids)].copy()

# Drop helper column
test_df_clean.drop(columns=["Complex_ID_lower"], inplace=True)

# Save the cleaned test file
test_df_clean.to_csv(output_path, index=False)

print(f"✅ Cleaned test file saved at: {output_path}")
print(f"🧹 Removed {len(test_df) - len(test_df_clean)} overlapping Complex_IDs")
print(f"✅ Final test set size: {len(test_df_clean)}")

✅ Cleaned test file saved at: /media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test_nonoverlapped.csv
🧹 Removed 770 overlapping Complex_IDs
✅ Final test set size: 5265

In [5]:
import pandas as pd
test = "/media/user/282895b1-543c-4689-9ced-b38fcef5e554/YASHI_ECIF/Merged_ECIF_RDKit_test_nonoverlapped.csv"
test_data = pd.read_csv(test)
test_data.shape

(5265, 1758)